### ISSUE TITLE
Set dataset for Update seems impossible

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [oxigraph/oxigraph#1000]
**Describe the bug**
On an [Update](https://docs.rs/oxigraph/0.3.22/oxigraph/sparql/struct.Update.html) methods provided to update dataset is [using_datasets_mut](https://docs.rs/oxigraph/0.3.22/oxigraph/sparql/struct.Update.html#method.using_datasets_mut) but it returns an empty iterator.
As the Iterator is non-mutable, it's impossible to add a new dataset.

Is it relevant to add Default dataset in the iterator ?

**Comment by MarcAntoine-Arnaud** [comment]
Why it's different from the [Query](https://docs.rs/oxigraph/0.3.22/oxigraph/sparql/struct.Query.html) API ?

**Comment by Tpt** [comment]
The main difference between SPARQL queries and updates is that there might be multiple update operations in a single "SPARQL update", each of the update being separated by `;`. Hence the iterator to iterate on each operation. Moreover, only the [DELETE/INSERT operations](https://www.w3.org/TR/sparql11-update/#deleteInsert) can have a custom dataset specified for the "WHERE" clause. Hence, the iterator only returns the dataset for these operations.

To make an example, this update `using_datasets_mut` will return an empty iterator:
```sparql
LOAD <http://example.com/>
```
but this one will return two elements:
```sparql
INSERT { ?s ex:p2 ?o } WHERE { s exp:p1 ?o };
DELETE { ex:s ex:p ex:o } WHERE {}
```

**Comment by MarcAntoine-Arnaud** [comment]
Its also posible to insert data to a graph using:
```sparql
INSERT DATA
{ 
  GRAPH <http://exmple.com> 
  {
     _:movie <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/metadata#Movie> ;
             <http://example.com/metadata#hasTitle> "My Movie Title" .
  }
}
```

It targets the right dataset, but the iterator is empty.
So I cannot validate rights against the query and the targeted graph/dataset.

**Comment by Tpt** [comment]
Indeed, the iterator only return the queried datasets, not the edited one. To expose that I believe we should figure out a new API (a lot of features like the default graph being the union of some graphs do not make sense for editing)

Oxigraph 0.4.0-rc implements `From<spargebra::Update>` on `oxigraph::Update`.
You should be able to parse the update with spargebra, manipulate it and then convert it to an oxigraph update.

0.4 alpha releases implement

**Comment by MarcAntoine-Arnaud** [comment]
Awesome, super I will bump to 0.4.0-rc.1 !
Thanks
