### ISSUE TITLE
Service Description

### ISSUE THREAD

**Issue by tpluscode** [oxigraph/oxigraph#1002]
**Is your feature request related to a problem? Please describe.**

Please add [SPARQL 1.1 Service Description](https://www.w3.org/TR/2013/REC-sparql11-service-description-20130321/). This allows users to only configure the query endpoint and discover the capabilities of an endpoint without the need to make assumptions and store separate values for Query and Update endpoints

**Comment by Tpt** [comment]
Done in v0.4.1
