### ISSUE TITLE
Need to update `latest` docker tag  which is currently 8 years old

### ISSUE THREAD

**Issue by yarikoptic** [oxigraph/oxigraph#1003]
Unfortunately I am not familiar much with the https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag used here, so didn't dare to provide a PR, but someone with a clue on this should update the https://github.com/oxigraph/oxigraph/blob/HEAD/.github/workflows/artifacts.yml#L315 I guess to avoid current situation that

![image](https://github.com/user-attachments/assets/287f7d3c-7620-4a72-97f6-43b8c75f4bd5)

so apparently who is pulling `:latest` get the `:eldest` ;)

**Comment by Tpt** [comment]
Thank you for this report!

`latest` currently points to the latest stable version that is currently 0.3.22 that got released 8 months ago. I hope to release 0.4.0 soon and `latest` will automatically point to it.

**Comment by yarikoptic** [comment]
oh, I should have figured it out - closing ;-)  
FWIW -- `latest` just [never returned](https://github.com/ReproNim/simple2_NIDM_examples/pull/16) on our sample query but latest tagged rc (not even the `main`) performed fine.
