### ISSUE TITLE
Can't serialize Triple / TripleRef using NTriplesSerializer

### ISSUE THREAD

**Issue by joepio** [oxigraph/oxigraph#1007]
Hi! Thanks for making this :) great to see there is an RDF lib now that rio is no longer maintained.

**Describe the bug**
I can't get the NTriplesSerializer to work. I keep getting type issues. Perhaps this is me just not understanding the library, sorry if that's the case!

**To Reproduce**
```rust
use oxrdf::NamedNodeRef;
use oxrdf::TripleRef;
use oxttl::NTriplesSerializer;

let mut formatter = NTriplesSerializer::new().for_writer(Vec::new());
let node = NamedNodeRef::new("test").unwrap();

// the trait bound `oxrdf::triple::TripleRef<'_>: std::convert::From<oxrdf::TripleRef<'_>>` is not satisfied
// the following other types implement trait `std::convert::From<T>`:
// `oxrdf::triple::TripleRef<'a>` implements `std::convert::From<&'a oxrdf::triple::Triple>`
// `oxrdf::triple::TripleRef<'a>` implements `std::convert::From<oxrdf::triple::QuadRef<'a>>`
// required for `oxrdf::TripleRef<'_>` to implement `std::convert::Into<oxrdf::triple::TripleRef<'_>>`
formatter.serialize_triple(TripleRef::new(node, node, node))?;

String::from_utf8(formatter.finish()).unwrap()
```

Things I tried:

- `into()`
- use `Triple.as_ref()` instead of `TripleRef`
- Some other things that didn't work :'(

**Comment by jonassmedegaard** [comment]
I guess your should try look at OxRDF I/O instead, which is literally described as "a set of parsers and serializers for RDF.
" :-)

**Comment by jonassmedegaard** [comment]
whoops, I realize now that it was me suggesting to use oxrdf. Sorry, my mistake!

**Comment by Tpt** [comment]
Thank you! Are you using a version of `oxrdf` compatible with `oxttl`? For example `oxttl` 0.1.0-rc.2 should be used with `oxrdf` 0.2.0-rc.2. To check it, just see if your Cargo.lock contains two versions of oxrdf (ba) or only one (good)

**Comment by hoijui** [comment]
Maybe this can also be closed now?

**Comment by Tpt** [comment]
Indeed. Thanks!
