### ISSUE TITLE
Register on Rust Awesome

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [oxigraph/oxigraph#1060]
It can be great to register to https://github.com/rust-unofficial/awesome-rust

**Comment by Tpt** [comment]
This is a great idea! Thank you! Feel free to do it.

**Comment by MarcAntoine-Arnaud** [comment]
submitted https://github.com/rust-unofficial/awesome-rust/pull/1833

**Comment by MarcAntoine-Arnaud** [comment]
Done
