### ISSUE TITLE
GeoSPARQL not working in Oxigraph 0.4.3

### ISSUE THREAD

**Issue by MadsHolten** [oxigraph/oxigraph#1089]
# Description

I'm having trouble getting GeoSPARQL functions to work correctly in Oxigraph 0.4.3. I have a dataset with queries that execute successfully on GraphDB, but they fail to produce the expected results in Oxigraph.

I've tried running Oxigraph both using Docker and from the command line, but neither approach seems to work. My understanding is that GeoSPARQL support should be enabled by default in Oxigraph.

To test this further, I created a simple "Bermuda test" with the following query:

```sparql
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?point 
WHERE {
  BIND("POLYGON ((-64.8 32.3, -65.5 18.3, -80.3 25.2, -64.8 32.3))" AS ?polygon)
  VALUES ?point { "POINT (-70.268555 25.522615)" "POINT (-60.996094 24.846565)" }
  FILTER(geof:sfWithin(?point, ?polygon))
}
```

This query checks if two points are located within a polygon representing Bermuda. GraphDB correctly identifies the first point as being inside the polygon and the second point as being outside. However, Oxigraph doesn't seem to process the geof:sfWithin function correctly.

<img width="625" alt="image" src="https://github.com/user-attachments/assets/3af16c88-9c2a-4da4-b256-5ebbbe50ae8b">

# Expected behavior

Oxigraph should correctly evaluate the geof:sfWithin function and return only the point that falls within the specified polygon.

# Actual behavior

Oxigraph returns no results.

# Steps to reproduce

Start Oxigraph 0.4.3 (using Docker or CLI).
Load the provided SPARQL query.
Execute the query and observe the results.
```sh
curl -X POST -H 'Accept: text/csv' -H 'Content-Type: application/sparql-query' --data 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> SELECT * WHERE { BIND("POLYGON ((-64.8 32.3, -65.5 18.3, -80.3 25.2, -64.8 32.3))" AS ?polygon) VALUES ?point { "POINT (-70.268555 25.522615)" "POINT (-60.996094 24.846565)" } FILTER(geof:sfWithin(?point, ?polygon)) }' http://localhost:7878/query
```

# Environment

Oxigraph version: 0.4.3
Operating system: Mac OS Sonoma 14.6.1
Deployment method: Docker / CLI

# Additional information

The same dataset and queries work correctly on GraphDB.
GeoSPARQL support is assumed to be enabled by default in Oxigraph.

**Comment by Tpt** [comment]
Hey! Thank you for this so well written bug report!

I think you encounter this because Oxigraph only allows typed literals in geosparql functions. The following query works (note the `geo:wktLiteral` datatypes):

```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?point
WHERE {
  BIND("POLYGON ((-64.8 32.3, -65.5 18.3, -80.3 25.2, -64.8 32.3))"^^geo:wktLiteral AS ?polygon)
  VALUES ?point { "POINT (-70.268555 25.522615)"^^geo:wktLiteral "POINT (-60.996094 24.846565)"^^geo:wktLiteral }
  FILTER(geof:sfWithin(?point, ?polygon))
}
```

**Comment by MadsHolten** [comment]
Thank you for the swift response! I can confirm that it now works when I run the server through the CLI. When running it in Docker I still don't get a result.

My own dataset already has typed literals so it worked when I added the typing to the constraint polygon 🚀

I still don't get a result if I try to calculate the distance between the two points though:

```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>

SELECT *
WHERE {
  BIND("POINT (-70.268555 25.522615)"^^geo:wktLiteral AS ?p1)
  BIND("POINT (-60.996094 24.846565)"^^geo:wktLiteral AS ?p2)
  BIND(geof:distance(?p1, ?p2, uom:metre) AS ?dist)
}
```

or

```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT *
WHERE {
  BIND("POINT (-70.268555 25.522615)"^^geo:wktLiteral AS ?p1)
  BIND("POINT (-60.996094 24.846565)"^^geo:wktLiteral AS ?p2)
  BIND(geof:metricDistance(?p1, ?p2) AS ?dist)
}
```

**Comment by Tpt** [comment]
> . When running it in Docker I still don't get a result.

Indeed, my bad, I forgot to enable the feature in the docker container

> I still don't get a result if I try to calculate the distance between the two points though:

Yes, these functions are not implemented yet. Only the `sf*` functions are implemented for the moment.

**Comment by MadsHolten** [comment]
Alright, thanks for the clarification! Will it work in JavaScript?

Thanks a lot for developing this great project!

**Comment by Tpt** [comment]
> Will it work in JavaScript?

Not yet but it should be easy to add. Will do it in the next release.

> Thanks a lot for developing this great project!

Thank you for this nice word!
