### ISSUE TITLE
please use newer bindgen

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#1112]
Debian builds now fail like this:
```
3664s The following warnings were emitted during compilation:
3664s 
3664s warning: oxrocksdb-sys@0.4.4: In file included from api/c.cc:3:
3664s warning: oxrocksdb-sys@0.4.4: /usr/include/rocksdb/db.h:14:10: fatal error: 'map' file not found
3664s warning: oxrocksdb-sys@0.4.4: #include <map>
3664s warning: oxrocksdb-sys@0.4.4:          ^~~~~
3664s warning: oxrocksdb-sys@0.4.4: 1 error generated.
3664s 
3664s error: failed to run custom build command for `oxrocksdb-sys v0.4.4 (/usr/share/cargo/registry/oxrocksdb-sys-0.4.4)`
```

I suspect it is caused by Debian moving to newer bindgen v0.70.1 - which is not your concern, but if you don't mind then it would be quite helpful if you could bump to using newer bindgen as well (because I don't have a clue how to juggle that).

**Comment by Tpt** [comment]
Thanks! I am going to investigate that

**Comment by Tpt** [comment]
This is weird, oxigraph `main` branch `Cargo.lock` uses `bindgen` 0.70.1 and works properly in the CI.

Can it be a build configuration issue where the compiler does not find C++ standard library for some reason?

**Comment by jonassmedegaard** [comment]
Thanks for looking, as sorry for wasting your time: I guess I misread those errors as being non-fatal after all (weird!), because the package has now regardless transitioned to Debian testing.
