### ISSUE TITLE
out of memory error when ttl does not have line endings

### ISSUE THREAD

**Issue by majidaldo** [oxigraph/oxigraph#1113]
**Describe the bug**
This is an edge case issue. I'm not sure if ttl format even allows this but the parser crashes after a certain number of triples.

**To Reproduce**
1. Which version of Oxigraph are you using? On which platform? 0.4.4
2. A command-line or a code snippet that triggers the bug.
```python
def gen(n):
    for i in range(n):
        yield f"<urn:test:subject:{i}>", f"<urn:test:predicate:{i}>", f"<urn:test:object:{i}>"


def ttl(n, sep='.\n'):
    _ = gen(n)
    _ = map(lambda t: ' '.join(t), _)
    _ = sep.join(_)
    if _: _= _+'.'
    return _

def test(*, n=100, sep='.\n'):
    _ = ttl(n, sep=sep)
    from pyoxigraph import parse, RdfFormat
    _ = parse(_, RdfFormat.TURTLE)
    _ = frozenset(_)
    print('n triples', len(_))


test(n=100_000, sep='.\n')
test(n=100_000, sep='.'  )

test(n=1000_000, sep='.\n')
test(n=1000_000, sep='.'  )
```
```
❯ python test.py
n triples 100000
n triples 100000
n triples 1000000
Traceback (most recent call last):
  File "C:\Users\aldo405\code\cls\semint\mapping\test.py", line 27, in <module>
    test(n=1000_000, sep='.'  )
  File "C:\Users\aldo405\code\cls\semint\mapping\test.py", line 19, in test
    _ = frozenset(_)
        ^^^^^^^^^^^^
OSError: Reached the buffer maximal size of 16777216
```
this error is specifically from [json_event_parser](https://docs.rs/json-event-parser/latest/src/json_event_parser/read.rs.html#88) but idk what it has to do with parsing ttl.

**Comment by majidaldo** [comment]
> Hey! This is error is from oxttl. The Ntriples format mandates that there is only a single triple per line and works by reading each line into a buffer before parsing. Here your last test call there is no line jump so rhe parser fills its buffer until reaching the safety measure I set to avoid out of memory error. This is weird the second test call is not faling with a syntax error. Let me check why.

...but i'm asking it to be parsed as ttl. i do get the right failure if the parsing format is ntriples.

**Comment by Tpt** [comment]
> ...but i'm asking it to be parsed as ttl. i do get the right failure if the parsing format is ntriples.

Indeed. My bad. I read your code too quickly. I am going to investigate that.
