### ISSUE TITLE
upload .ttl file instead of insert query

### ISSUE THREAD

**Issue by vojtechmusilek** [oxigraph/oxigraph#120]
Is it possible to send .ttl file text as payload? Described here: [9 SPARQL 1.1 Graph Store HTTP Protocol](https://www.w3.org/TR/2013/REC-sparql11-overview-20130321/#sparql11-graphstore-http-protocol)
I tried:
```
POST /update HTTP/1.1
Host: localhost:7878
Content-Type: text/turtle
Content-Length: 193260

@prefix brick: <https://brickschema.org/schema/Brick#> .
@prefix soda_hall: <https://brickschema.org/schema/1.0.2/building_example#> .
soda_hall:ahu brick:isLocationOf soda_hall:exhaust_fan_E12,
        soda_hall:exhaust_fan_E13,
....
```
Response is: `Not supported Content-Type given: text/turtle`

Am I doing something wrong or is is really not suppored? And if not, do you consider implementing it?

**Comment by Tpt** [comment]
Hi! Yes, [the SPARQL graph store protocol](https://www.w3.org/TR/sparql11-http-rdf-update/) is supported. You should use the `/store` endpoint for that.

For example, `curl -f -X POST -H 'Content-Type:application/n-triples' --data-binary "@MY_FILE.nt" http://localhost:7878/store?graph=http://example.com/g` inserts into the `http://example.com/g` graph and `curl -f -X POST -H 'Content-Type:application/n-triples' --data-binary "@MY_FILE.nt" http://localhost:7878/store?default` inserts into the default graph.

**Comment by vojtechmusilek** [comment]
Perfect, thanks!

**Comment by vojtechmusilek** [comment]
Hi, im trying this with .ttl files and header 'Content-Type:text/turtle' and im getting '415 Unsupported Media Type'
Are Turtle files supported or only n-triples?

**Comment by Tpt** [comment]
Hi! N-Triples, Turtle and RDF/XML should be supported. Would it be possible for you to provide me the HTTP headers you use to reproduce this problem (a Curl call is fine)?

**Comment by vojtechmusilek** [comment]
This is the call with response (i censored the ip adress)
```
> curl -f -X POST -H 'Content-Type:text/turtle' --data-binary "test.ttl" http://*******:7878/store?default
curl: (22) The requested URL returned error: 415 Unsupported Media Type
```
I also tried application/turtle but same result

**Comment by Tpt** [comment]
Thank you! I have not manage to reproduce the problem. But I still have two ideas:
* Maybe quote `http://*******:7878/store?default`. Some shells don't like "?" and so might just target `http://*******:7878`. `curl -f -X POST -H 'Content-Type:text/turtle' --data-binary "@test.ttl" 'http://localhost:7878` return a 415 error.
* Maybe use `"@test.ttl"` instead of `"test.ttl"` to load properly the `test.ttl` file.

**Comment by vojtechmusilek** [comment]
Thanks, i did not know that `@` in the data binary parameter is needed.

I found some pretty interesting stuff, apparently `" "` and `' '` are two different things in Windows cmd or at least when using curl.
It looks like it skips the content type header when its in single quotes. Therefore the error 415.

This works: `curl -f -X POST -H "Content-Type:text/turtle" --data-binary "@test.ttl" "http://****:7878/store?default"`
