### ISSUE TITLE
Inlining language tags for String literals

### ISSUE THREAD

**Issue by thadguidry** [oxigraph/oxigraph#162]
Will Oxigraph eventually be able to inline language tags for string literals?

On a [recent thread](https://lists.wikimedia.org/hyperkitty/list/wikidata@lists.wikimedia.org/thread/CVFUG43C3GCCZ7UZU52JCSXZXOZLLPPS/), David Causse mentioned something that got me wondering about Oxigraph's roadmap as well...

>> On Fri, Nov 5, 2021 at 3:46 PM Thomas Douillard <thomas.douillard@gmail.com> wrote:
>>
>>   [...] 
>>
>>    But a query planner/rewriter should be able to detect a pattern like « filter lang() = "en" » to take advantage of such an index ?
>>
>>
>With how blazegraph works it is hard to apply filters on literals unless the data to filter is "inlined" in the btree. Unfortunately what blazegraph offers is inlining the whole literal not just the lang tag and inlining all string literals is definitely not possible for wikidata, the btree would explode.
Perhaps there are other triple stores that could inline solely the language tag that would make this query faster?

**Comment by Tpt** [comment]
Oxigraph inlines the language tag as soon as it fits in 16 bytes when encoded in UTF-8. So, it's a yes for all common language tags. Inside of the storage trees, the language tagged strings are encoded in the "type byte" > "language tag" > "value" order so this kind of efficient filter should be quite easy to implement with a prefixed search.

**Comment by thadguidry** [comment]
@Tpt Your reply will be useful to add to a FAQ or the Wiki or Docs.

**Comment by Tpt** [comment]
@thadguidry Yes, I should definitely write a document describing Oxigraph internals. I have opened #163 about it.

**Comment by Tpt** [comment]
This is now described [in the architecture document](https://github.com/oxigraph/oxigraph/wiki/Architecture).
