### ISSUE TITLE
Publish binary with each release

### ISSUE THREAD

**Issue by vemonet** [oxigraph/oxigraph#179]
Hi @Tpt , I could not find where to download the `oxigraph_server` binary, is it published somewhere? 

Otherwise would it be possible to publish the `oxigraph_server` binary with each release? Like I did here: https://github.com/vemonet/oxigraph/releases/tag/v0.2.5

This will allow to easily download it directly to run it, instead of needing to install all dependencies and build

**Comment by Tpt** [comment]
Currently we have prebuilt versions of:
* [The server on docker](https://hub.docker.com/r/oxigraph/oxigraph).
* [pyoxigraph wheels on pypi](https://pypi.org/project/pyoxigraph/).
* [npm package on npm](https://www.npmjs.com/package/oxigraph).
* The [homebrew tap](https://github.com/oxigraph/homebrew-oxigraph) does not provide prebuilt binaries yet.

Indeed, it might be nice to build also easy to use executable for Oxigraph server (taking into account ABI issues, especially on Linux).

**Comment by vemonet** [comment]
@Tpt you mean you would need to create different binary for different platforms? Like `linux-amd64` , `linux-arm`, etc?

I was looking into a specific use-case where oxigraph seems to be a really good candidate: a lightweight embedded triplestoreMore specifically, my current use case is to run it as an embedded triplestore in a JupyterLab/VisualStudio Code workspace (a docker container running in a kubernetes cluster)

I already integrated oxigraph using https://github.com/jupyterhub/jupyter-server-proxy , the user can start and access the SPARQL endpoint YASGUI directly from the JupyterLab Launcher

The installation in the Dockerfile was a piece of cake with the pre-built binary:

```
RUN wget -O /usr/local/bin/oxigraph_server https://github.com/vemonet/oxigraph/releases/download/v0.2.5/oxigraph_server && \
    chmod +x /usr/local/bin/oxigraph_server
```

The challenge now is to find how to connect to the embedded endpoint with libraries and code. In my case I cannot just use the URL on which I access the YASGUI interface, because it is behind the JupyterLab proxy requiring a password (there might be some way to workaround this, but the goal would be to have a seamless integration without needing to fight with proxies and authentication)

And it might not be the only use-case where accessing the endpoint URL directly is not possible/not recommended (for security reason you might want to avoid exposing services)

So I was wondering if that would make sense to be able to connect to the Oxigraph database directly from it's database folder?

I am thinking in particular about doing it with python bindings, but there could also be bindings to JavaScript. This way a python/javascript user will be able to have a quick and easy access to a performant triplestore locally without hassle

For example:

```
store = LocalStore('./oxigraph_data')
store.add(Quad(NamedNode('http://example.com'), NamedNode('http://example.com/p'), Literal('1')))
list(store.query('CONSTRUCT WHERE { ?s ?p ?o }'))
```

Where `oxigraph_data` is the folder containing the data for a triplestore

I know that oxigraph is still in heavy development, it seems you are in a transition from SledStore to Rocksdb (pyoxigraph still use SledStore, but the oxigraph server uses RocksDB), and my knowledge of Rust is still limited. 

So I don't know if this proposition makes sense regarding the direction you are taking with the oxigraph ecosystemIf that is something you are interested in, I would be willing to contribute (I have knowledge of python/typescript, and would be interested to learn more about Rust)

Additionally I'll be interested to know if you think there are major bugs or missing features in SPARQL that we need to be aware of, before using Oxigraph? :)

**Comment by Tpt** [comment]
> @Tpt you mean you would need to create different binary for different platforms? Like linux-amd64 , linux-arm, etc?

Yes, exactly. With all dependencies included in the binary to make it as portable as possible.

>  My current use case is to run it as an embedded triplestore in a JupyterLab/VisualStudio Code.

Very nice!

Indeed, if you are using python, using pyoxigraph directly might be the most convenient way. 

If you want to try with Oxigraph v0.2 and Sled:
```python
from pyoxigraph import *
store = SledStore('./oxigraph_data')
store.add(Quad(NamedNode('http://example.com'), NamedNode('http://example.com/p'), Literal('1')))
list(store.query('CONSTRUCT WHERE { ?s ?p ?o }'))
```
should work without trubles indeed.

> I know that oxigraph is still in heavy development, it seems you are in a transition from SledStore to Rocksdb (pyoxigraph still use SledStore, but the oxigraph server uses RocksDB), and my knowledge of Rust is still limited.

The previous versions where allowing to use both Sled and RocksDB. It was plainful to maintain both storages at the same time so I choose to stick to one and RocksDB is currently the only stable one. I might change back Oxigraph to Sled if it progresses a lot but it is likely it won't happen in at least the next year.

> Additionally I'll be interested to know if you think there are major bugs or missing features in SPARQL that we need to be aware of, before using Oxigraph? :)

All SPARQL 1.1 query (including federation) and update should be supported outside of two things.
* `SERVICE` call targetting variables (e.g. `SERVICE ?myService { ?s ?p ?o }`).
* Property path with`*` or `?` with both departure and arrivial unbounded (e.g. `SELECT * { ?s :myProp* ?o }`). But it works when one  of the variable is already bound (e.g. `SELECT * { ?s :myProp2 ?o . ?s :myProp* ?o }`).

**Comment by vemonet** [comment]
Thanks for the details! It was not obvious we could provide the path when creating the Store, I don't think it is in the current pyoxigraph documentation. But that is exactly what I was looking for

I tried it successfully with 0.2.5, then I checked the `master` branch and realized you already implemented the switch to RocksDB!

I installed it from source and it worked fine too, nice job!

```python
from pyoxigraph import *

store = Store('oxigraph_data')
store.add(Quad(NamedNode('http://example.com3'), NamedNode('http://example.com/p3'), Literal('3'), NamedNode('http://example.com/g')))
print(str(store))
```

We are considering using this for courses and workshops on RDF knowledge graphs

If you want to check oxigraph embedded in JupyterLab you can find it here: https://github.com/MaastrichtU-IDS/jupyterlab (I have tried Blazegraph too, but it does not integrate as well as Oxigraph)
```bash
docker run --rm -it -p 8888:8888 -e JUPYTER_TOKEN=password ghcr.io/maastrichtu-ids/jupyterlab:knowledge-graph
```


For building binaries, do you have an idea of an approach you would prefer? I found 2 that seems to make it easy to do it via GitHub Actions, but I am not sure how reliable they are, and you might have already something in mind:
* https://github.com/marketplace/actions/rust-release-binary
* https://github.com/zackify/flydb/blob/master/.github/workflows/build-binary.yml

**Comment by Tpt** [comment]
> I tried it successfully with 0.2.5, then I checked the master branch and realized you already implemented the switch to RocksDB!
> I installed it from source and it worked fine too, nice job!

Great! I plan to release a first beta for the 0.3 release soon. I am currently improving some code details and working on documentation, changelog...

> We are considering using this for courses and workshops on RDF knowledge graphs

Amazing!

>For building binaries, do you have an idea of an approach you would prefer?

I started working on something as part of #174. This PR provides a beginning of Linux x86 binary. I am also using this PR to explore compilation of pyoxigraph to arm64. I got something working in an emulated environment but it's very slow (the build takes 3h). I tried some cross compilation but cross-compiling C++ + Rust is challenging.

**Comment by jeremiahpslewis** [comment]
FYI Oxigraph server binary is now available as a Julia binary package on all platforms supported by julia. :) See https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl

```julia
using Pkg
Pkg.add("oxigraph_server_jll")
```

**Comment by Tpt** [comment]
I have just releases v0.3.0-beta.1 (and the follow-up v0.3.0-beta.2 that fixes crates.io build). Both releases have now pre-built binaries artefacts. For example https://github.com/oxigraph/oxigraph/releases/tag/v0.3.0-beta.1

@jeremiahpslewis If you plan to package Oxigraph 0.3 for Julia, there is no dependency anymore on openssl, Oxigraph now uses [rustls](https://github.com/rustls/rustls).

Feel free to reopen this issue if I am missing something.

**Comment by vemonet** [comment]
Thanks a lot @Tpt ! I will try it as soon as I have a use-case, and create issues or pull requests if needed

Right now all popular triplestores I know are in Java... Most are not really open source, and no binding to popular languages

I must say having such a nicely designed triplestore, running natively, with smartly defined bindings to python/JS, would be quite game changer for using RDF data more easily!
