### ISSUE TITLE
v0.3.0 does not bind to 0.0.0.0:7878 

### ISSUE THREAD

**Issue by saminahbab** [oxigraph/oxigraph#191]
Hello, 
I have a kubernetes deployment with a service to this database. 
In v0.2.5 I have the command defined  as this 

```
          command:
            - oxigraph_server
            - --bind=0.0.0.0:7878
            - --file=/data

```

and the services defined within the environment work as expected. 
However when making the version upgrade to v0.3.0, removing the bind argument 
(because it is default) makes the database container refuse connections.
```
          command:
            - oxigraph_server
            - --location=/data
            - serve

```

I would have thought that expected behaviour would be that the server binds in exactly the same way as in the first example by default. 
Is this not the case? 

Thank you for your time! 
Samin

**Comment by Tpt** [comment]
Hi! I believe it's because Oxigraph default "bind" argument value is "localhost:7878" and you were binding to "0.0.0.0:7878" previously. I think that by default Docker exposes 0.0.0.0 to the outside but not 127.0.0.1 (localhost).

**Comment by saminahbab** [comment]
Ah, I understand that now, makes sense. 

Am I right in saying the argument to specify binding has been removed for v0.3.0? 
If so, it would be helpful if default also bind to 0.0.0.0:7878, as in a Kubernetes (and I guess other orchestration) environment it uses 0.0.0.0. 

Cheers for the great work! the benchmarks are looking really good!

**Comment by Tpt** [comment]
> Am I right in saying the argument to specify binding has been removed for v0.3.0?

No, it's still there and still called "bind". So `oxigraph_server serve --location=/data --bind=0.0.0.0:7878` should work with v0.3. 
It is only displayed in the cli help message if we select the "subcommand". So `oxigraph_server --help` does not show it but `oxigraph_server serve --help` do. It's a shortcoming of the library we use to handle all the cli related stuff.

> Cheers for the great work! the benchmarks are looking really good!

Thank you! And I only scratched the surface on what is doable. Analytical query performances are still very bad compared to what should be not too hard to archive.

**Comment by Tpt** [comment]
@saminahbab I hope Oxigraph 0.3 is running well for you now. I close this issue. Feel free to open it again if you encounter more problems.

**Comment by saminahbab** [comment]
Hey @Tpt, that should be fine, sorry that I did not follow up on this! Busy week with a new job! `oxigraph_server --help` confused me because I assumed specifying binding was essentially taken away. Your comments explain evertything and I will try v0.3 again 
Thank you so much for your time! Happy to close the issue.
