### ISSUE TITLE
Bindgen dependency

### ISSUE THREAD

**Issue by jeremiahpslewis** [oxigraph/oxigraph#196]
Hey! I'd love to be able to cross-compile oxigraph to make binaries available for many platforms via Julia's Yggdrasil [(link)](https://github.com/JuliaPackaging/Yggdrasil), but keep on running into various issues with dependencies that bindgen introduces (clang) and issues that bindgen has with cross-compiling. Do you have any thoughts on how one might be able to get this to work?

**Comment by Tpt** [comment]
Hi! Cross compiling with bindgen is indeed a nightmare. I tried to get something working to release binaries on different architecture but never managed to make it work properly. I currenty [use docker-qemu in the CI](https://github.com/oxigraph/oxigraph/blob/cbccdfba867204ce4b20b6fc16e37a30719f90eb/.github/workflows/release.yml#L81) to avoid the cross compilation issues. What is fun  is that the mapping between C types and Rust types depends on the architecture so it's not possible to package into Oxigraph a bindgen output that would work properly on all archs.

There seems to be a lot of discussions around these issue online, I have not found the time to read them carefully yet and see if there is something that might work. If you manage to find something I would love to tweak Oxigraph build to make it work.

**Comment by jeremiahpslewis** [comment]
Ok, thanks! I've spent a good bit of time looking into this and it's relatively hopeless given my skillset. But `cargo install` works fine, so for the moment, I'll close this.
