### ISSUE TITLE
I can't use oxigraph in my project

### ISSUE THREAD

**Issue by Anhod** [oxigraph/oxigraph#198]
I added the line **oxigraph = "0.3.1"**  in Cargo.toml，and then run **cargo build**，But during compilation，there is a fault with **oxiri-0.2.2**
![image](https://user-images.githubusercontent.com/52108493/163955843-0f3791b7-c52f-4972-bb9a-3c15ff8c03e1.png)

**Comment by Tpt** [comment]
@Anhod Hi! Sorry for that and thank you for trying Oxigraph.

It's stange. I just checked my clone of OxIRI 0.2.2 and I don't see this typo in my clone. Are you sure to have not modified the file?
A quick way to check it would be to delete the `C:\Users\ACER\.cargo\registry` directory and build again.

**Comment by Anhod** [comment]
> @Anhod Hi! Sorry for that and thank you for trying Oxigraph.
> 
> It's stange. I just checked my clone of OxIRI 0.2.2 and I don't see this typo in my clone. Are you sure to have not modified the file? A quick way to check it would be to delete the `C:\Users\ACER\.cargo\registry` directory and build again.

I solve it！Thank you！but unfortunately，there exists a new problem as follows：
![image](https://user-images.githubusercontent.com/52108493/163973515-66616c68-a2ad-4107-8d3f-7d62d87fccda.png)
Does this have anything to do with the rust version?

**Comment by Tpt** [comment]
Great! 

>  Does this have anything to do with the rust version?

Yes, Oxigraph targets the latest stable rust version.

**Comment by Anhod** [comment]
> Yes, Oxigraph targets the latest stable rust version.
Compiled successfully！Can I use oxigraph directly like this in my own project？
![image](https://user-images.githubusercontent.com/52108493/163994670-7d615a5e-7fd1-4ee9-bdc9-29c5602cde7f.png)
Cargo.toml is：
![image](https://user-images.githubusercontent.com/52108493/163994747-10b5b04f-4bde-4fc6-a735-80099bd0a233.png)

**Comment by Tpt** [comment]
> > Yes, Oxigraph targets the latest stable rust version.
> > Compiled successfully！Can I use oxigraph directly like this in my own project？

Great! Amazing! Yes, it's exactly what I am doing in a lot of places.

**Comment by Anhod** [comment]
I may have caused you a lot of trouble.
Because of the requirements,I need to modify the source code of oxigrah.So I download it locally,and then I want to use this as a extern crate.The usual practice is that I can add the path of oxigraph in **Cargo.toml**,but it seems oxigraph is a virtual manifest type workspace,so I don't how to use it.Looking forward to your answer!
![image](https://user-images.githubusercontent.com/52108493/164154656-f3d44759-93fd-4717-b938-93a515c7c979.png)
![image](https://user-images.githubusercontent.com/52108493/164154701-e908419d-dedf-4010-8ae6-af41bf39233c.png)

**Comment by Tpt** [comment]
> Because of the requirements,I need to modify the source code of oxigrah.So I download it locally,and then I want to use this as a extern crate.The usual practice is that I can add the path of oxigraph in **Cargo.toml**,but it seems oxigraph is a virtual manifest type workspace,so I don't how to use it.Looking forward to your answer!

No problem, I am happy to see Oxigraph users! You should set the path to the actual Oxigraph crate so instead of `../oxigraph` you should use `../oxigraph/lib`.

PS : `extern crate` prelude is not required anymore with Rust 2018 and 2021.

**Comment by Anhod** [comment]
> > Because of the requirements,I need to modify the source code of oxigrah.So I download it locally,and then I want to use this as a extern crate.The usual practice is that I can add the path of oxigraph in **Cargo.toml**,but it seems oxigraph is a virtual manifest type workspace,so I don't how to use it.Looking forward to your answer!
> 
> No problem, I am happy to see Oxigraph users! You should set the path to the actual Oxigraph crate so instead of `../oxigraph` you should use `../oxigraph/lib`.
> 

Amazing！I got it！

**Comment by Tpt** [comment]
I allow myself to close this issue. Feel free to open it again (or create a new one) if you have more questions/encounter more problems. Thank you again for trying Oxigraph!
