### ISSUE TITLE
Publish oxigraph::io as seperate crate.

### ISSUE THREAD

**Issue by damooo** [oxigraph/oxigraph#201]
`oxigraph::io` provides structs and functions for parsing from, serializing to, syntaxes that can be determined at runtime. This functionality is general, and is most helpful in many cases, and a seperate crate without rocksdb dependencies will help.

**Comment by Tpt** [comment]
Hi! Thank you for investigating Oxigraph. There is the [Rio library](https://github.com/oxigraph/rio) that provides plain [Turtle](https://crates.io/crates/rio_turtle) and [RDF/XML](https://crates.io/crates/rio_xml) parsers in Rust. It's what Oxigraph relies on. However the API of Rio is not as nice as the one in Oxigraph and does not uses the data structures defined by Oxigraph and [oxrdf](https://crates.io/crates/oxrdf). I plan to improve it in the future (in a few months/years, definitely not short-term).

**Comment by damooo** [comment]
`oxigraph::io` seems can be used as layer over `oxrdf` and `rio`. Though `rio` provides specialized parsers, ability to specify syntx at runtime, and parsing/serializing into run-time specified syntax, which can be determined from mimetype/file-extn, etc.. are some fundamental operations dealing with io of rdf.

If it is feasible some `oxio`, crate factored out from `oxigraph::io`, helps great.

**Comment by Tpt** [comment]
> If it is feasible some `oxio`, crate factored out from `oxigraph::io`, helps great.

Sure! Let's add this to the next relase TODO.

**Comment by Tpt** [comment]
Done in 0.4.0-alpha.1: https://crates.io/crates/oxrdfio
