### ISSUE TITLE
unclear error message

### ISSUE THREAD

**Issue by pchampin** [oxigraph/oxigraph#203]
Consider the following query:
```
SELECT * {
  ?s ?p ?o.
  BIND (?o as ?s)
}
```
The error message is not very informative
```
error at 4:2: expected [_]
```
Contrast this with sparql.org's error message:
```
BIND: Variable used when already in-scope: ?s in BIND(?o AS ?s)
```

NB: in this minimal example, it is quite obvious what the error is. But I ran into this problem with a long query where it was much less obvious.

**Comment by Tpt** [comment]
Indeed SPARQL parser errors are awful at the moment. I have opened #129 about it.
