### ISSUE TITLE
Build Issue with clang 13.1 on macOS M1

### ISSUE THREAD

**Issue by novocodev** [oxigraph/oxigraph#207]
I am experiencing an issue building oxigraph

The issue appears to be related to the version of clang, below is my dev configuration

Hardware: Apple MacBook Pro M1 chip
OS: macOS Monterey 12.3.1
cargo: 1.60.0
clang: 13.1.6

Im building for an iOS target

The command I'm running is: cargo +nightly build --release -Z build-std --target x86_64-apple-ios-macabi

The underlying clang command:

`clang" "-O3" "-fPIC" "--target=x86_64-apple-ios13.0-macabi" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk" "-fembed-bitcode" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/Users/foo/projects/bar-rs/target/x86_64-apple-ios-macabi/release/build/ring-1a3ac6774bf49e76/out/aesni-x86_64-macosx.o" "/Users/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesni-x86_64-macosx.S`

The error is: clang: error: invalid version number in '--target=x86_64-apple-ios13.0-macabi'

Search results suggest that the 13.0 target has been removed from clang 13.1 and that the clang --target should be 13.1

What I can't figure out is what config to update to achieve that

**Comment by Tpt** [comment]
Hi! This seems to have been fixed in the `cc` crate by [this commit](https://github.com/rust-lang/cc-rs/commit/faef75008a1a802ec24f5ec2ed7731e26b02fb5e) that has been released as part of the latest `cc` version.

Running `cargo update && cargo +nightly build --release -Z build-std --target x86_64-apple-ios-macabi` might work.

**Comment by Tpt** [comment]
Closing, I believe that the `cc` change fixed this problem
