### ISSUE TITLE
Publish Python documentation of readthedocs

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#209]
Readthedocs [now allows to compile Rust code](https://github.com/PyO3/maturin/issues/371#issuecomment-963004915). It might be nice to host the python documentation there instead of our custom website. [maturin also provides some documentation](https://github.com/PyO3/maturin/blob/main/guide/src/sphinx.md).

**Comment by bollwyvl** [comment]
Semi-related: there has been some recent evolution of getting [rust-based packages built for pyodide](https://github.com/pyodide/pyodide/issues/2816), which means the docs site could eventually include a live demo, a la [sympy, numpy, pandas](https://twitter.com/SylvainCorlay/status/1540271410261774336), etc. (disclaimer: helped build some of those :blush:).

**Comment by Tpt** [comment]
Done. The documentation is now on readthedocs
