### ISSUE TITLE
Cannot build server: couldn't read oxrocksdb-sys/rocksdb/src.mk

### ISSUE THREAD

**Issue by jgeluk** [oxigraph/oxigraph#213]
After a fresh git clone of the repo doing `cargo run --bin oxigraph_server` you get this error:

```
   Compiling oxrocksdb-sys v0.3.3 (/Users/jacobus/Work/oxigraph/oxrocksdb-sys)
error: couldn't read oxrocksdb-sys/rocksdb/src.mk: No such file or directory (os error 2)
  --> oxrocksdb-sys/build.rs:47:27
   |
47 |     let mut lib_sources = include_str!("rocksdb/src.mk")
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `oxrocksdb-sys` due to previous error
```

Would be good to document what the prerequisites are for a local build.

**Comment by jgeluk** [comment]
Duplicate of #206 but still good to document the requirement to use git submodule commands in the README.md file

**Comment by Tpt** [comment]
Thank you for trying Oxigraph! The documentation is indeed still lacking in this area. I have just pushed f8db6abd6647c766b549a518ca6d266750e7a921 to help fix that. What do you think about this update?

**Comment by edmondchuc** [comment]
I just ran into this issue as well. 

@Tpt your new instructions were useful, thanks. I ran `git submodule update --init` on the existing repository and it was able to compile successfully after the submodules were fetched.

**Comment by Tpt** [comment]
I am closing this issue now that the documentation has been updated. Feel free to reopen it if you feel something is still missing.
