### ISSUE TITLE
Citing Oxigraph

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [oxigraph/oxigraph#240]
Hi!,

I am wondering how can we cite oxigraph in our academic publication. I think that linking Oxigraph to Zenodo (like [RDFlib](https://github.com/RDFLib/rdflib/issues/1454) recently did) and have a DOI would be nice.

Julián

**Comment by Tpt** [comment]
That's a great point! I have made the work for Zenodo to generate DOI for each version. I have also wrote #241 to add a citation file.

**Comment by ArenasGuerreroJulian** [comment]
Thanks! :)

**Comment by Tpt** [comment]
Done and working: https://doi.org/10.5281/zenodo.7408022
