### ISSUE TITLE
Turtle parsing bug

### ISSUE THREAD

**Issue by PetterBMarkussen** [oxigraph/oxigraph#252]
Uploading of a turtle file to a running Oxigraph server is having an issue when literal values goes over several lines. 

Example: 
I have a tripple that I uploaded to the oxigraph server running on localhost:port: 

 ns1:subj ns2:value " This values goes over 
several lines"

When I send a SELECT ?value WHERE {ns1:subj ns2:value ?value} to this endpoint, I dont get a "\n" for the ?value. The whole string is return in a concatinated form without the \n. 

This does not happen however if I upload the triples as a n-triples.

**Comment by Tpt** [comment]
Thank you for your reply!

> I guess the serializer in RDFLib only uses "" for literals.

That's stange. I just tried with rdflib 6.2 and the serialization seems to work properly:
```python
>>> import rdflib
>>> g = rdflib.Graph()
>>> g.add((rdflib.URIRef("http://example.com/"), rdflib.URIRef("http://example.com/"), rdflib.URIRef("http://example.com"))
>>> g.serialize().strip()
'<http://example.com/> <http://example.com/> """foo\nbar""" .'
```

**Comment by Tpt** [comment]
Closing this issue for this inactivity to clean up the issue list.  Feel free to open it again if you need so.
