### ISSUE TITLE
Implement Jena-like `loop:` "service" to support lateral joins

### ISSUE THREAD

**Issue by hobofan** [oxigraph/oxigraph#267]
We are currently trying to use oxigraph for a project where GraphQL-like query structures are transformed into SPARQL queries. 

E.g. a typical high-level query for that would be "Query 10 of A (filtered by X), and for each of them query 5 of B"

However we are running into the problem that SPARQL currently doesn't support "lateral joins" (see this thread for deeper explanation: https://github.com/w3c/sparql-12/issues/100), which means that the required "10 of" isn't correctly expressable as a LIMIT in a SPARQL query.

I think out of the solutions proposed in the linked thread, the `loop:` service enhancer that Jena recently added (https://jena.apache.org/documentation/query/service_enhancer.html), is one of the better options.

I did already try to implement that functionality for oxigraph for some time now, but after trying out a few different things, I'm not sure how it would be best implemented or if that would even be possible with oxigraph's current architecture. Any pointers on the topic would be greatly appreciated! :)

**Comment by Tpt** [comment]
> I did already try to implement that functionality for oxigraph for some time now, but after trying out a few different things, I'm not sure how it would be best implemented or if that would even be possible with oxigraph's current architecture. Any pointers on the topic would be greatly appreciated! :)

Yes, tweaking the SPARQL evaluation requires to change code in a lot of places and it's definitely not convenient. It might be possible to do just like Jena and (ab)use the `SERVICE` system using the [`ServiceHandler`](https://docs.rs/oxigraph/latest/oxigraph/sparql/trait.ServiceHandler.html) trait but it won't be very efficient.

Thank you for the pointers, I'm going to have a look at them.

**Comment by Aklakan** [comment]
Hi, I am the developer of the service enhancer plugin. in the Jena implementation, SERVICE <loop:> is not handled dynamically during execution but during static query optimization. In general, at execution time it is already too late to get looping behavior. It needs to be ensured that the left-hand side is execution first and that the bindings are fed to the SERVICE <loop:> {} expression.

In general, it may happen that a SPARQL join is executed by evaluating the lhs and rhs independently and their respective result sets are merged in a post-processing step.

In Jena, there fortunately already existed the OpSequence algebra operator which already provided the behavior suitable for lateral joins.

For example, given
```SERVICE { gp1 SERVICE <loop:http://foo/bar> { gp2 }}

then the default algebra in Jena looks like
```
OpJoin(
  opOf(gp1),
  OpService(loop:http://foo/bar, opOf(gp2)))
```
and the post processing by [TransformSE_JoinStrategy](https://github.com/apache/jena/blob/162f0ddfa2764ce926a2a00f59f6261657f29c5f/jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/algebra/TransformSE_JoinStrategy.java#L54) yields
```
OpSequence(
  opOf(gp1),
  OpService(loop:http://foo/bar, opOf(gp2)))
```

In addition, the transformer also adjusts variable scopes - not sure how this is handled by oxigraph.
But the main point is, that the algebra has to be "fixed" for lateral joins before passing it on to the execution engine.

**Comment by Tpt** [comment]
@Aklakan Thank you for this detailed explanation. It makes a lot of sense. Congratulation on the documentation of this feature. It is amazing! Thank you!

> In general (at least with Jena), it may happen that a SPARQL join is executed by evaluating the lhs and rhs independently and their respective result sets are merged in a post-processing step.

Yes, it's also what Oxigraph does in the general case. It puts lhs or rhs in a hash table and streams through the other input. There are some heuristics in the query planner to use a "for loop join"/`OpSequence` instead. 

There is no `OpSequence` in Oxigraph SPARQL algebra yet (I have found no need for having it explicit yet in the algebra) but it exists in the query plan data structures. So, it should not be too hard to add.

> In addition, the transformer also adjusts variable scopes - not sure how this is handled by oxigraph.

Currently very naively. The `project` node of the algebra is considered a scope boundary and there is some specific code to deal with scoping issues related to `OPTIONAL`. Adding lateral queries support would probably require to tweak some stuff in this area.

**Comment by Tpt** [comment]
I see two way forward with this:

1. Implement the same "hack" as Jena: a magic "loop:" service that, if it contains a subquery binds the outer variables inside the subquery.
2. Implement something similar to what is suggested in w3c/sparql-12/issues/100
For example: `{foo} {LATERAL SELECT ?v WHERE {bar}}` would run for each tuple result of `foo` the pattern `bar` with all tuples set by `foo` already bound at the beginning of `bar` evaluation and add `?v` to the tuple results. This way the behavior seems fairly explicit and clear.

**Comment by Tpt** [comment]
After thinking about it with @hobofan I believe the best way to implement it is to move forward with `{foo} {OX_LATERAL SELECT ?v WHERE {bar}}` that binds all variables from `foo` at the beginning of `bar` and optionally `{foo} {OX_LATERAL ?v1 ?v2 SELECT ?v WHERE {bar}}` that only binds `?v1` and `?v2`.

The `OX_` prefix is there to make explicit it's an Oxigraph extension that might evolve or be replaced by a future SPARQL specification.

**Comment by Tpt** [comment]
After more reflection I believe I am changing my mind.

The syntax `{foo} {OX_LATERAL SELECT ?v WHERE {bar}}` is not great: it collides with the implicit semantic of SPARQL that `{foo} {bar}` is the bottom up join of `foo` and `bar`. On the other side if someone write `foo OPTIONAL { bar }` there is an implicit "lateral/sequence" semantic: `foo` is evaluated and for each tuple of `foo` `OPTIONAL { bar }` is evaluated.

So, something like `{foo} OX_LATERAL ?v1 ?v2 SELECT ?v WHERE {bar}` would make more sense.

**Comment by afs** [comment]
Reading this discussion and #274 has been very helpful - thank you.

**Comment by hobofan** [comment]
Closing this as what I was looking for with LATERAL joins has been implemented now 🎉 https://github.com/oxigraph/oxigraph/pull/336
