### ISSUE TITLE
Server: Allows SPARQL querying from the command line

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#269]
It might be nice to be able to execute SPARQL queries from the cli without having to spawn a server.
For example (not sure it's the best interface):
`cat my-query.rq | oxigraph_server --location XXXXX query --output-format=csv > result.csv`

**Comment by RichDijk** [comment]
Would be convenient indeed.
In this use case the server executes the sparql. To me the server looks heavy for this purpose because only a store.query with output formatting is required.

**Comment by joepie91** [comment]
As there is currently an `oxigraph_server query` command, is this issue resolved, or is there still some detail left to implement?

**Comment by Tpt** [comment]
This issue should definitely be closed. Thank you for spotting it!
