### ISSUE TITLE
Error while storing triples

### ISSUE THREAD

**Issue by RichDijk** [oxigraph/oxigraph#283]
Thank you for making pyoxigraph. 
We want to use pyoxigraph for persistance with acceptable performace in Python. When reading larger nt files (> 350MB) on Windows 10 using Python 3.10 and pyoxigraph 0.3.8 with

`store.load(f"./filename.nt",  "application/n-triples")`

I do get consequently the error : 

> fatal runtime error: Rust cannot catch foreign exceptions

How can I debug this better for locating the reason for this error?

**Comment by Tpt** [comment]
Hi! Thank you! Sorry for that, it sounds like an exception from the C++ code of RocksDB. RocksDB is not supposed to throw exceptions but maybe it does. The `load` method is transactional and quite memory intensive. The `bulk_load` method removes this restriction and is less memory consuming and faster.

**Comment by RichDijk** [comment]
Thank you, that works indeed better.
Even 3.6 GB ttl file is no problem and is parsed in 5 minutes on a small laptop. 
Great!

**Comment by Tpt** [comment]
I believe this could be now closed (feel free to open it again if it's not the case)
