### ISSUE TITLE
Expose bulk load in the HTTP API

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#290]
The HTTP API of Oxigraph server is only exposing the transactional API. It should expose bulk load too.

**Comment by Tpt** [comment]
@PetterBMarkussen Thank you for the idea! I am not sure that the step "uploading into a directory" is required. The bulk loader should be able to ingest an HTTP request content without troubles.

**Comment by PetterBMarkussen** [comment]
Ok. I guess we need to change the load_dataset function inside the lib/src, s.t. it uses the buld_loader instead of the transaction function?  @Tpt

**Comment by Tpt** [comment]
> Ok. I guess we need to change the load_dataset function inside the lib/src, s.t. it uses the buld_loader instead of the transaction function?

I don't think you have to change Oxigraph library (the `lib` directory) but just change inside of the HTTP server (`server/src/main.rs`) the implementation of `POST` and `PUT` requests on `/store` to use `store.bulk_loader().load_dataset` instead of `store.load_dataset`.

**Comment by PetterBMarkussen** [comment]
Ok, thanks @Tpt . I changed the store.load_dataset() to store.bulk_loader().load_dataset() for POST, but memory is still going to 25 GB and beyond when I build the image again. Do you have any advice how I can lower the memory for the API? 

I changed the code here:

line 466: else if let Some(format) = DatasetFormat::from_media_type(&content_type) {
                    if let Err(e) =
                        store.bulk_loader().load_dataset(BufReader::new(request.body_mut()), format, None)
                    {
                        return bad_request(e);
                    }

**Comment by Tpt** [comment]
@PetterBMarkussen Sorry for that. Your change seems correct. Just to be sure, are you loaded the data to disk by setting the `--location` (or `-l`) option when launching the server or to memory (the default behavior)?

**Comment by PetterBMarkussen** [comment]
Hi. Yes, I am starting the container by using the following command: docker run --rm -p 7878:7878 oxigraph/oxigraph --location /data serve --bind 0.0.0.0:7878

Inside the container: /data , I can see that it writes to disk, but no drop in memory.

**Comment by Tpt** [comment]
@PetterBMarkussen Thank you! May you try to limit memory consumption by replacing `store.bulk_loader().load_dataset` by something like  `store.bulk_loader().set_max_memory_size_in_megabytes(1000).load_dataset`?

The bulk loader also tends to use a lot of memory to build the index BTree into memory before flushing them to disk, especially if a lot of CPU cores are available on the machine.

**Comment by PetterBMarkussen** [comment]
Hi again @Tpt Now I have tested out several scenarios. Just for some info; my machine has 16 threads and 2.5 GHz as base speed and 32 GB ram available.

I have tested the server with running max_memory=1000 as well as 500, but still a hard time indexing 33 M tripples. Maybe it is the internal RockDB that is using so much memory?

**Comment by Tpt** [comment]
Thank you! It's strange. I just tried to load https://archive.org/details/wikidata-json-20160620 (68GB) on my laptop (8 threads, 32GB of RAM, Arch Linux) with a similar patch as yours and it ran with less than 2GB of RAM. Which OS are you using?

**Comment by PetterBMarkussen** [comment]
Hi @Tpt . Ok, so you tested this triplett-file with a curl POST request? Interesting. 

I am using WSL2 for windows, and maybe this is the issue, as you said. Any yes, writing to disk occurs very sporadically. It usually comes in bursts, when I watch the IO read/write. I will try to see how I can fine tune this. Thanks for the advice @Tpt !

**Comment by Tpt** [comment]
> I am using WSL2 for windows, and maybe this is the issue, as you said.

Thank you! I have never tried Oxigraph with it. Maybe the [library I use](https://docs.rs/sysinfo/latest/sysinfo/) to gather system information is not working properly on it.

> Any yes, writing to disk occurs very sporadically. It usually comes in bursts, when I watch the IO read/write. 

I/Os are supposed to be bursty when the loader flushes from memory to disk. If these burts are quick it's likely our problem is not I/O bottleneck. I am going to write a pull request with my customization of the server for bulk I/O. This way we would be able to make sure we have the exact same code.

> Ok, so you tested this triplett-file with a curl POST request? Interesting.

Beware, I had to tweak it a bit because of some syntax errors. I also tried with a big file generated using [BSBM generator](http://wbsg.informatik.uni-mannheim.de/bizer/berlinsparqlbenchmark/spec/BenchmarkRules/index.html#datagenerator).

**Comment by PetterBMarkussen** [comment]
Hi, 

Ok, nice! In the meantime, I will check how WSL2 is affecting the IO read/write performance operation

**Comment by PetterBMarkussen** [comment]
Hi @Tpt . Sorry for late answer, but I had to try and test some scenarios with the no_transaction. I have had a hard time to post .nt files to this endpoint. What syntax are you using when sending curl POST? 

I am currently using this: curl -f -X POST -H "Content-Type:application/n-triples" --data-binary "@$windowsdir/examplefile1.nt" "http://localhost:7878/store?no_transaction"

But I am not able to get these tripples into the store. I am doing a basic query to the endpoint after the curl command, but with no response. Using SELECT ?a WHERE ?a ?b ?c in the query, so it should output some tripples.

**Comment by Tpt** [comment]
Hi @PetterBMarkussen ! Thank you for trying again!

> What syntax are you using when sending curl POST?
> I am currently using this: curl -f -X POST -H "Content-Type:application/n-triples" --data-binary "@$windowsdir/examplefile1.nt" "http://localhost:7878/store?no_transaction"
>But I am not able to get these tripples into the store. I am doing a basic query to the endpoint after the curl command, but with no response. Using SELECT ?a WHERE ?a ?b ?c in the query, so it should output some tripples.

Yes, it's a trap of the [SPARQL 1.1 Graph Store HTTP Protocol](https://www.w3.org/TR/sparql11-http-rdf-update/). When you POST a graph serialization (N-Triples, Turtle, RDF/XML...) a new named graph is created and its name is returned in the `Location` header of the response that has a HTTP 201 Created status. The query endpoint`/query` also queries the default graph only by default, hidding the inserted triples because they are in a named graph.

There are a few possible ways to make it work like you want.
* In the SPARQL query use `SELECT ?a WHERE { GRAPH ?g { ?a ?b ?c }}` to query all graphs and not only the default graph.
* Use `/query?union-default-graph` instead of `/query` to query all graphs in the dataset by default instead of only the default graph.
* Use `curl -f -X POST -H "Content-Type:application/n-triples" --data-binary "@$windowsdir/examplefile1.nt" "http://localhost:7878/store?default&no_transaction"` (note the added `?default` in the URL) to ask to add the triples to the default graph.
* Use `application/n-quads` content-type instead of `application/n-triples`. All N-Triples files are a valid N-Quads files where triples are in the default graph.

Side note: It's better to use `-T "$windowsdir/examplefile1.nt" ` instead of `--data-binary "@$windowsdir/examplefile1.nt"` because `-T` properly streams the given file whereas `--data-binary` buffers the complete file into memory. I just realized I was using `--data` in the server README, I have just updated it #302

**Comment by PetterBMarkussen** [comment]
Hi @Tpt . Excellent! Now it works fine. Using WSL2 with 10 GB memory limit and it works fine. I think that -T <file> did the trick! As you said, the --data-binary buffers it into memory. Now I am able to index the .nt files without having any memory problems.  I must say that it is a bit counter intuitive from the SPARQL 1.1 standard to create a named graph even though I did not specify it in the POST.  

Thanks for helping me out!

**Comment by Tpt** [comment]
@PetterBMarkussen Amazing! Thank you for opening this bug, it made me improve both code and documentation so it has been definitely worth it. Feel free to close this issue if you feel everything is fine on this side.

**Comment by Tpt** [comment]
Closing this issue now. Feel free to open it again if useful.
