### ISSUE TITLE
oxigraph server doesn't load store

### ISSUE THREAD

**Issue by RichDijk** [oxigraph/oxigraph#292]
Should the following work without any configuration?

`
oxigraph_server_v0.3.8_x86_64_windows_msvc.exe -l ./store serve 
`

The sparql end point that appears at localhost:7878 does not give any triple. When I check using the store using cli, data exists.

**Comment by Tpt** [comment]
Yes, it should if you point the `-l` option to the correct data dir just like you did.

Just in case: if you have loaded data into a named graph then you should specifically target it inside of the SPARQL query using the `GRAPH` keyword.

**Comment by RichDijk** [comment]
No, I have loaded the data with store.bulk_load()

**Comment by Tpt** [comment]
Thank you! Have you loaded the data to the default graph or a named graph? If the data is loaded into a named graph you should use the `GRAPH` operator of SPARQL queries to query it (or add `?using-union-graph=true` to the SPARQL endpoint URL)

**Comment by RichDijk** [comment]
In the default graph

**Comment by RichDijk** [comment]
It works now. My fault because the path was set incorectly.
