### ISSUE TITLE
Experiment with a Sled-based storage

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#30]
[Sled](https://sled.rs/) is a key-value store written in Rust that seems to offer promising performances. It would be nice to experiment using it as an alternative to RocksDB to allow building Oxigraph without a dependency on a C++ compiler.

**Comment by Tpt** [comment]
I have pushed a first version of a Sled based store. Write speed is lagging behind RocksDB and I have not implemented yet transaction support.

**Comment by dwhitney** [comment]
This sounds cool. I'm curious if this work in a browser? I believe RocksDB
does (haven't tried it either).

**Comment by Tpt** [comment]
Sled is done to write its data on disk (just like RocksDB). I'm not sure what would be the advantage of using it in a browser compared to the in-memory store if the data are going to stay in-memory anyway.

But it would be indeed great to have some [WASI](https://wasi.dev/) support to be able to run it in NodeJS without requiring a native Node extension. The new Oxigraph nodeJS package currently only works with the in memory store.

**Comment by dwhitney** [comment]
Oh I thought RocksDB could run on top of indexeddb or something.

**Comment by Tpt** [comment]
I was not aware of that. Do you have a link?

Are you thinking about [LevelIUp](https://github.com/Level/levelup) that provides wrapper on top of LevelDB and RocksDB for NodeJS and on top of IndexedDB for web browser?

**Comment by dwhitney** [comment]
I'm probably just wrong
