### ISSUE TITLE
SPARQL: restrict unicode escapes?

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#376]
It seems like the community concensus on SPARQL is moving to only allow unicode escapes (`\uXXXX` and `\UXXXXXXXX`) in IRI and literal values just like Turtle instead of allowing it everywhere like the SPARQL 1.1 specification. See, for example, [this commit](https://github.com/w3c/rdf-tests/commit/b9c27c3d73b3387ea130c6b96af0dd076c9bbeac).

Oxigraph currently allows escapes everywhere but it might be nice to restrict it too for two reasons:
1. To avoid a preprocessing pass on the query string before actual parsing just to do the unescaping.
2. Ease the work of people who might want to sanitize queries before giving them to oxigraph. The keywords would be always written in plain ASCII instead of being maybe obfuscated using unicode escapes.

This would be a breaking change against our stability policy on SPARQL 1.1 so, imho, we should make it only if this restriction is also done in future SPARQL specifications.

**Comment by afs** [comment]
FWIW ARQ changed to reflect community consensus. The strict SPARQL parsers do have the spec form. 

No issues arose. No users reported anything. Not sure anyone noticed!

**Comment by Tpt** [comment]
Done in 0.4.0-alpha.1
