### ISSUE TITLE
advertise conda installation

### ISSUE THREAD

**Issue by majidaldo** [oxigraph/oxigraph#418]
thanks for creating a [conda package](https://github.com/conda-forge/oxigraph-feedstock)! should be in the [installation docs](https://pyoxigraph.readthedocs.io/en/stable/) though.

**Comment by Tpt** [comment]
Thank you for raising this topic. This package is maintained by @bollwyvl and not by me so I have no control about it at all and can't make sure it stays up to date. This state is very different from the Pypi packages that are automatically published by Oxigraph CI/CD. Hence, I am a bit afraid of advertising it as a recommended installation option.

**Comment by bollwyvl** [comment]
Yep, I do what I can, but c+rust * py * os * arch * SSL sometimes leaves me
in a spot where we either have to hold for upstream packages (like
compilers), skip versions, or drop configurations. The most recent gap
ended up being some missing c packages on windows, which are particularly
boring and discouraging.

Always happy for more hands on the feedstock, of course, but certainly not
expecting anyone to do any more work than gives them value.

**Comment by majidaldo** [comment]
> Yep, I do what I can, but c+rust * py * os * arch * SSL sometimes leaves me in a spot where we either have to hold for upstream packages (like compilers), skip versions, or drop configurations. The most recent gap ended up being some missing c packages on windows, which are particularly boring and discouraging. Always happy for more hands on the feedstock, of course, but certainly not expecting anyone to do any more work than gives them value.

what i know is that the conda team is always looking to generate conda packages from native package formats. So what works now is Python (obviously), and R. Julia is WiP. Rust should be of interest.

I think conda is ideal for this mixed language situation.
