### ISSUE TITLE
query result 'promise' in internal format

### ISSUE THREAD

**Issue by majidaldo** [oxigraph/oxigraph#424]
The bottleneck for high performance io is the serialization/deserialization process.

It would be nice if the query result of  sparql `construct` can be in the form of a 'promise', that, when given to the `Store.load` method it would be equivalent to an sparql `insert` (the data didn't leave the db).

perhaps something like `Store.bulk_quad_add` could be made to improve performance.

**Comment by Tpt** [comment]
Hi @majidaldo! Thank you for your interest in Oxigraph.

> It would be nice if the query result of sparql construct can be in the form of a 'promise', that, when given to the Store.load method it would be equivalent to an sparql insert (the data didn't leave the db).

I see the point. But, genuine question, in the case of the source and target storages are the same, why not just use a SPARQL insert operation? And if they are different I believe that the existing API should be fairly efficient (at least in Rust).

> perhaps something like Store.bulk_quad_add could be made to improve performance.

Something in this direction [is already available in the Rust API](https://docs.rs/oxigraph/latest/oxigraph/store/struct.BulkLoader.html#method.load_quads).

**Comment by majidaldo** [comment]
> I see the point. But, genuine question, in the case of the source and target storages are the same, why not just use a SPARQL insert operation? And if they are different I believe that the existing API should be fairly efficient (at least in Rust).

Right...

> > perhaps something like Store.bulk_quad_add could be made to improve performance.
> 
> Something in this direction [is already available in the Rust API](https://docs.rs/oxigraph/latest/oxigraph/store/struct.BulkLoader.html#method.load_quads).

Well in the python bindings there's just `Store.add(1quad)`. Invoking this function repeatedly I'm assuming will be slower than `quads` -> `serialize(quads,bytes,format)` -> `Store.bulk_load(bytes, format)` .


(can close if no plan)

**Comment by Tpt** [comment]
> Well in the python bindings there's just Store.add(1quad). Invoking this function repeatedly I'm assuming will be slower than quads -> serialize(quads,bytes,format) -> Store.bulk_load(bytes, format) .

That's a good point. I should definitely add a `bulk_add` function in Python that adds all the quads from a given iterator. Thank you!

**Comment by Tpt** [comment]
Done in #426
