### ISSUE TITLE
Add CORS header to the SPARQL endpoint

### ISSUE THREAD

**Issue by ktk** [oxigraph/oxigraph#458]
**Is your feature request related to a problem? Please describe.**
Yes, the problem I encountered is the lack of Cross-Origin Resource Sharing (CORS) support in Oxigraph SPARQL endpoint. I was trying to fetch data from the server in a client-side web application, but the browser blocked the request due to the same-origin policy.

**Describe the solution you'd like**
I would like to have built-in CORS support in Oxigraph, allowing developers to configure CORS settings, such as whitelisted domains and supported HTTP methods. This would enable client-side web applications to interact with the server seamlessly, without facing issues related to the same-origin policy. Quick fix would be to provide a flag to enable it for all.

**Describe alternatives you've considered**
As an alternative, I considered setting up a proxy server to handle the CORS-related headers and requests. However, this adds unnecessary complexity to the architecture and can be less efficient than having built-in CORS support in the server software itself.

**Additional context**
CORS is hell...

**Comment by Tpt** [comment]
Thank you! I should definitely add basic CORS support for such use cases. What about adding a `--cors` option to the Server?

**Comment by ktk** [comment]
Sounds like a good idea to me. The scenario I have is that I have an internal oxigraph server in my home for IoT devices & I built a simple frontend to fetch some observations from cubes I write. So I indeed only use unauthenticated oxigraph with direct access for the simple chart page.

In production setups I put our Trifid in front which does CORS but that seems like overkill here.

**Comment by Tpt** [comment]
@ktk Very nice usecase. Thank you for trying Oxigraph in such settings! Here is a pull request #461. I hope to cut a release with it this week.

**Comment by ktk** [comment]
Excellent, looking forward! Will do a screencast about my IoT stuff later this week.

**Comment by Tpt** [comment]
Amazing! I have releases v0.3.15 with this feature.

**Comment by ktk** [comment]
Just tested, works great thanks!
