### ISSUE TITLE
decimal incorrectly parsed to 0

### ISSUE THREAD

**Issue by pchampin** [oxigraph/oxigraph#463]
**Describe the bug**
Oxigraph parses the following xsd:decimal `0.1000000000000000055` as 0.

**To Reproduce**
Run the following SPARQL query :
```
SELECT (0.1000000000000000055 as ?x) {}
```

It seems that the problem comes from the number of digits in the fractional part.
Any decimal with 18 digits or less in the fractional part is correctly parsed,
but any decimal with 19 digitis or more is parsed as 0.

**Comment by Tpt** [comment]
That's interesting. The decimal parsing code only uses `checked_` arithmetic operation. I'm going to investigate it.
