### ISSUE TITLE
Target WASM runtimes where `wasm-bindgen` is not available

### ISSUE THREAD

**Issue by Luca8991** [oxigraph/oxigraph#471]
**Is your feature request related to a problem? Please describe.**
I'm trying to run an RDF database and expose a SPARQL endpoint on an [Internet Computer canister](https://internetcomputer.org/how-it-works/canister-lifecycle/). For this reason, the features I'd need the most from **oxigraph** are the **database** and the **SPARQL parser**.
However, but I keep getting this error when deploying it:
```
Module imports function '__wbg_getRandomValues_3774744e221a22ad' from '__wbindgen_placeholder__' that is not exported by the runtime.
```
From what I understand, this means that the canister runtime doesn't expose `wasm-bindgen` library.

**Describe the solution you'd like**
I'm not that expert in Rust and compiling it to WASM, hence I don't know exactly if it would be possible to avoid the usage of `wasm-bindgen` and what effort it could it take.

**Describe alternatives you've considered**
I've tried [sophia](https://github.com/pchampin/sophia_rs), which compiles and runs smoothly, but is missing the SPARQL parser. Is there a way to use oxigraph's parser with sophia?

**Additional context**
I'd suggest you to dive into the [Internet Computer documentation](https://internetcomputer.org/docs), because I see a great potential here to enable decentralized RDF databases that can have various applications like decentralized social media platforms, etc.

**Comment by hobofan** [comment]
The issue is not with `wasm-bindgen` (you will likely need that if your compile target is WASM), the problem is with the usage of `getrandom` for generating random values for Blank Nodes.

See https://docs.rs/getrandom/latest/getrandom/#webassembly-support for more context. It looks like your WASM runtime environment (the IC canister) doesn't expose a `Crypto.getRandomValues` function to the WASM module.

AFAIK if the `js` feature flag would be removed here (https://github.com/oxigraph/oxigraph/blob/main/lib/Cargo.toml#L51-L53), it would be possible to register a custom random number generator for non-JS WASM runtimes. (I guess oxigraph would need to introduce a feature flag that's turned on by default to allow this in a backwards compatible manner).

From what I know from working with Web3 systems in the past, random numbers are notoriously hard/slow to generate in the runtimes of those systems (I would assume that IC is no different there). So if you want to embark further on this topic, there is a good chance that this could be quite complicated and/or may not yield a result that has a good performance profile.

**Comment by Luca8991** [comment]
Thanks @hobofan!
Given the complications that could come out from porting oxigraph to the IC by registering a custom random number generator and probably also changing other things, you wouldn't recommend to spend time on it, right?
In this case, do you have some ideas and/or suggestions on how to create and expose an RDF database on the IC without rewriting everything from scratch?

**Comment by Tpt** [comment]
Hi @Luca8991! thank you for trying Oxigraph.
Hi @hobofan! Thank you for your detailed answer.
Oxigraph compiled to wasm32-unknown-unknown relies on 2 JS method: `Crypto.getRandomValues` for randomness (used to generate random variable and blank node ids and to power some SPARQL functions like `RAND` and `UUID`) and `Date.now` for the SPARQL `NOW` function.
It would be great to have a `no_js` feature Oxigraph to allow compiling without JS dependencies on wasm32-unknown-unknown. The main challenge imho is to replace the random blank node generation with some system that would generate unique blank node identifiers. For variables, it's only used in the parser so knowing which variable names are already used in order to properly generate new variable names should not be hard. And for the SPARQL functions `RAND`, `UUID` and `NOW` we could maybe just disable them.  For blank nodes, using a global counter and hope for no conflict might be a way to go.

**Comment by hobofan** [comment]
> Given the complications that could come out from porting oxigraph to the IC by registering a custom random number generator and probably also changing other things, you wouldn't recommend to spend time on it, right?

I mean in the end it depends on your motivation. As I don't have any experience with IC concretely (and also don't want to spend time digging into it), I can't judge how much effort it would ultimately be. (Who knows, maybe IC does something really clever with random numbers and exposes a great interface for them 🤷)

>  In this case, do you have some ideas and/or suggestions on how to create and expose an RDF database on the IC without rewriting everything from scratch?

I *guess* an alternative route (which is probably also quite some work) would be to fork oxigraph and rip out the parts that require random number generation. AFAIK that would "only" be the support for generating anonymous blank nodes. I'm unsure how many parts of the oxigraph internals rely on the generation of those, and for how many of those there is an adequate workaround, or functionality would have to be sacrificed.

Another possible alternative would be to ensure unique anonymous blank nodes via a mechanism that doesn't rely on random numbers (e.g. https://github.com/Stebalien/snowflake).

**Comment by Luca8991** [comment]
Thanks for the precious advices @Tpt and @hobofan! I've created a fork at [omnia-network/ic-oxigraph](https://github.com/omnia-network/ic-oxigraph) in which I ported the necessary functions to make Oxigraph run on the Internet Computer runtime. Now it compiles and apparently runs correctly!

I'd be really thankful if you could give it a quick look and tell me if I need to adjust something. Here's the relevant commit: https://github.com/omnia-network/ic-oxigraph/commit/fb8406e1bbf300486f7510ffd2cb99674179c72a

**Comment by Tpt** [comment]
@Luca8991 It looks great! For the next breaking Oxigraph release we might:
- add to `oxigraph` and `oxsdatatypes` a `js` feature to enable usage of `js-sys` for random and time. It should be disabled by default.
- introduce something like `register_custom_getrandom` for the "now" operation to allow providing a custom implementation of now.
I believe it would cover the "internet computer" use case.
What do you think?

**Comment by Luca8991** [comment]
> add to `oxigraph` and `oxsdatatypes` a `js` feature to enable usage of `js-sys` for random and time. It should be disabled by default.

Does this mean that if I don't enable the `js` feature I won't target WASM?

> introduce something like register_custom_getrandom for the "now" operation to allow providing a custom implementation of now.

Sounds great! Will there also be the possibility to "register" a custom `Date::now()` implementation, so that we can use the [ic_cdk::api::time](https://docs.rs/ic-cdk/latest/ic_cdk/api/fn.time.html) function when using oxigraph on the Internet Computer?

Also, the maximum compiled WASM size supported by the IC is **2MB** (they're working on extending it as far as I know), and this makes the compiled WASM that uses the oxigraph library pretty "huge" (~ 4.5MB). It can anyway be deployed on the IC with `gzip`, but is there a way to reduce the library size? Maybe by adding optional features that one can choose?

If you've also took a look at the fork I created, you've probably noticed that I've removed a lot of folders that I don't need (`oxrocksdb-sys`, `python`, `server`, etc.) and this probably will make it hard to merge oxigraph again into it in the future to get updates, etc. Is there a better way to keep the repo simple but also easily updatable?

I'm also getting some errors when running `cargo test` in the repository where I use the ic-oxigraph library, and I think that's because the test doesn't target `wasm32-unknown-unknown` by default. The errors come from [rocksdb.rs](https://github.com/omnia-network/ic-oxigraph/blob/main/lib/src/storage/backend/rocksdb.rs) file and are related to `libc` missing or similar. Do you have suggestions on how to solve this?

**Comment by Tpt** [comment]
>> add to oxigraph and oxsdatatypes a `js` feature to enable usage of `js-sys` for random and time. It should be disabled by default.
>
> Does this mean that if I don't enable the `js` feature I won't target WASM?

It means that it will target WASM but without asusming that a JS runtime is availlable. So, it would work with e.g. the "Internet Computer".

>> introduce something like register_custom_getrandom for the "now" operation to allow providing a custom implementation of now.
>
> Sounds great! Will there also be the possibility to "register" a custom Date::now() implementation, so that we can use the [ic_cdk::api::time](https://docs.rs/ic-cdk/latest/ic_cdk/api/fn.time.html) function when using oxigraph on the Internet Computer?

Yes, exactly. It's the goal!

> Also, the maximum compiled WASM size supported by the IC is 2MB (they're working on extending it as far as I know), and this makes the compiled WASM that uses the oxigraph library pretty "huge" (~ 4.5MB). It can anyway be deployed on the IC with gzip, but is there a way to reduce the library size? Maybe by adding optional features that one can choose?

Yes, optional features are a great idea. For example we might allow to not compile all parsers and serializer. I am not sure which component takes the most space. Here are [some tips on reducing the compiled code size](https://rustwasm.github.io/docs/book/reference/code-size.html).

> If you've also took a look at the fork I created, you've probably noticed that I've removed a lot of folders that I don't need (oxrocksdb-sys, python, server, etc.) and this probably will make it hard to merge oxigraph again into it in the future to get updates, etc. Is there a better way to keep the repo simple but also easily updatable?

That sounds like a good idea. I already do something similar in Oxigraph RocksDB fork. I wrote [a script that removes the files I do not care about](https://github.com/oxigraph/oxigraph/blob/main/oxrocksdb-sys/trim_rocksdb.sh). This way I can easily pick a new rocksdb release, apply on top of it some patches and then do a final commit with the cleanup script.

> I'm also getting some errors when running cargo test in the repository where I use the ic-oxigraph library, and I think that's because the test doesn't target wasm32-unknown-unknown by default. The errors come from [rocksdb.rs](https://github.com/omnia-network/ic-oxigraph/blob/main/lib/src/storage/backend/rocksdb.rs) file and are related to libc missing or similar. Do you have suggestions on how to solve this?

I believe `cargo-test` does not work with wasm. There are multiple tools, [one for WASM+JS](https://rustwasm.github.io/docs/wasm-pack/commands/test.html) and [one for WASM+WASI](https://bytecodealliance.github.io/cargo-wasi/testing.html). I run [the WASI one in the CI](https://github.com/oxigraph/oxigraph/blob/a25bf5591953dcf75fb6ee241cfee3b8c3f583d5/.github/workflows/tests.yml#L162).

**Comment by Luca8991** [comment]
> Here are [some tips on reducing the compiled code size](https://rustwasm.github.io/docs/book/reference/code-size.html).

Thanks a lot for this resource! I reduced the WASM size by almost 50% and I didn't use all the optimizations available! So I guess the WASM size won't be a problem for now.

> I believe cargo-test does not work with wasm. There are multiple tools, [one for WASM+JS](https://rustwasm.github.io/docs/wasm-pack/commands/test.html) and [one for WASM+WASI](https://bytecodealliance.github.io/cargo-wasi/testing.html). I run [the WASI one in the CI](https://github.com/oxigraph/oxigraph/blob/a25bf5591953dcf75fb6ee241cfee3b8c3f583d5/.github/workflows/tests.yml#L162).

I can't use WASI because I'm getting errors regarding some methods imported from the IC SDK, that are not available in that WASM+WASI tests runtime.
I solved the problem by removing every line that was targeting another target than WASM (basically every line with `#[cfg(not(target_family = "wasm"))]` attribute) and removed every `#[cfg(target_family = "wasm")]` attribute to make the related line being compiled by default. You can see it in [this diff](https://github.com/omnia-network/ic-oxigraph/compare/7eecb726414b2d1ea7c240ea4b524f796a778f31...omnia-network:ic-oxigraph:94aa71392e093abc4f2072afb44443d220328f2a).

So now running `cargo test` works again. However, I don't feel it's good, also because writing a script that removes the unneeded parts like the one you mentioned becomes quite hard. It would have to go through all the code to find the lines with a different target and remove/adapt them as I did manually. Do you have some suggestions on how improve this?

**Comment by Tpt** [comment]
Done in 0.4.0-alpha.1. The `"js"` feature needs to be enable for integration into `js-sys` and a hook point exists for "now" support: https://github.com/oxigraph/oxigraph/tree/main/lib/oxsdatatypes#datetimenow-behavior
