### ISSUE TITLE
The SPARQL `query` should override the `options`, not the other way around

### ISSUE THREAD

**Issue by pchampin** [oxigraph/oxigraph#50]
The [documentation of `QueryOption`](https://docs.rs/oxigraph/0.1.1/oxigraph/sparql/struct.QueryOptions.html) states:

> [the values set by `with_default_graph` and `with_named_graph`] override the `FROM` and `FROM_NAMED` elements of the evaluated query.

I think is wrong, as it breaks the general expectation that a local configuration should have precedence over a global configuration. In my view, the query string is "more local" than the `QueryOptions`. I expect that the latter could be set once and for all and reused for several queries in a given application or module.

**Comment by Tpt** [comment]
Hi! I definitely agree with you on the general rule. However, doing so would make two use cases difficult to implement:

1. Implementation of the SPARQL protocol [that states that the `default-graph-uri` and `named-graph-uri` parameters should override the `FROM` and `FROM NAMED` parameters](https://www.w3.org/TR/sparql11-protocol/#dataset).
2. Access control where the lib user wants to forbid querying some named graphs.

**Comment by pchampin** [comment]
Ok, those are very valid use cases.

I still suggest that you make it explicit and salient  in the documentation of `prepare_query` and `query` that `options` overrides `query`. Currently, one has to dig into the doc of `QueryOption` to find out.

**Comment by Tpt** [comment]
Yes, definitely. I am going to do that.

PS: have you seen [oxrdflib](https://pypi.org/project/oxrdflib/)?

**Comment by Tpt** [comment]
Graph overriding won't be part of the `QueryOption` API anymore in Oxigraph 0.2. A new API is going to be provided as part of the `Query` type. So, there won't be any ambiguity anymore.
