### ISSUE TITLE
maybe support ustore as alternative to RocksDB

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#511]
I just stumbled upon ustore, claiming several times faster read and write than RocksDB in their youtube video, and with attention to [graphs](https://github.com/unum-cloud/ustore#graphs).

Perhaps that's interesting for oxigraph?

They are apparently actively working on [Rust bindings](https://github.com/unum-cloud/ustore/issues/238).

**Comment by Tpt** [comment]
Hi! Thank you for the suggestion! "ustore" seems to be an abstraction layer on top of various pluggable key value stores including RocksDB. There is also their key value store "udisk" they claim is faster than RocksDB but it does not seems open-source. So, sadly, it seems it won't help Oxigraph. I do not see the point of using "ustore" as an abstraction layer if we will going to end up using RocksDB anyway.

Please reopen this issue if you disagree with my assessment (I have not had a very deep look at ustore/udisk so I might fooling myself).

**Comment by jonassmedegaard** [comment]
I believe you are mistaken: Notice at https://unum-cloud.github.io/ustore/#id5 how *one* backend is RocksDB but another is their own in-house udisk which is much faster.

**Comment by Tpt** [comment]
@jonassmedegaard Yes, indeed, they claim that udisk is much faster. But sadly [it seems closed source](https://github.com/unum-cloud/udisk) so does not fit RocksDB requirement. But maybe it has been open sourced somewhere else I have not seen. Do you have more information on this side?

**Comment by jonassmedegaard** [comment]
oh crap, you are right - I missed that little detail :-(
