### ISSUE TITLE
Merge Rio parsers into Oxigraph

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#535]
The [Rio repository](https://github.com/oxigraph/rio) duplicates a lot of Oxigraph features (RDF model with `rio_api::model` vs `oxrdf`, test tooling...). It would be great to merge the two repositories together.

**Comment by arenas-guerrero-julian** [comment]
Hi @Tpt 

Is the parallelization of N-Triples parsing (as described [here](https://github.com/oxigraph/rio/issues/81#issuecomment-1348418753)) considered in this issue?

Thanks,
Julián

**Comment by arenas-guerrero-julian** [comment]
Thanks @Tpt. That would be great, I also think that would significantly speed up parsing
