### ISSUE TITLE
Consider having async stores and SPARQL evaluation

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#54]
It would be nice to allow stores and SPARQL evaluation to be asynchronous. I see three use cases:
* Implementing a web-compatible store based on [IndexDB](https://developer.mozilla.org/docs/Web/API/IndexedDB_API) that has only an async API.
* Allow distributed storage with system like [TiKV](https://tikv.org/).
* Allow HTTP async clients inside SPARQL query (useful to avoid blocking the evaluation thread or to provide a web implementation using [fetch](https://developer.mozilla.org/docs/Web/API/Fetch_API).

**Comment by adamemerson** [comment]
I'd really like this. And currently even something like wrapping calls in spawn_blocking doesn't work, since all the handles use Rc everywhere instead of Arc.

**Comment by Tpt** [comment]
Hi! `spawn_blocking` should work if you don't try to share parsed or prepared SPARQL query between threads. If not, it's a bug I need to fix.

**Comment by theduke** [comment]
> Hi! `spawn_blocking` should work if you don't try to share parsed or prepared SPARQL query between threads. If not, it's a bug I need to fix.

`spawn_blocking` by nature requires the future to be `Send`, because the task is offloaded to different (blocking) threads by the runtime.

**Comment by theduke** [comment]
I'm also interested in this.

The simplest route to something operational would be to just do the processing in dedicated threads and communicate via channels.

That would work just fine for servers, but not for WASM with some kind of persistence (IndexDB, file storage APIs, ...), which is also a use case I am very interested in.

**Comment by Tpt** [comment]
> spawn_blocking by nature requires the future to be Send, because the task is offloaded to different (blocking) threads by the runtime.

Yes, definitely. But, if I I understand utures properly, it does not prevent the content of the future to use not-send elements as soon as they does not cross yield boundaries. The Oxigraph server code used `spawn_blocking` to run SPARQL queries this way without problems.


> The simplest route to something operational would be to just do the processing in dedicated threads and communicate via channels.
> That would work just fine for servers, but not for WASM with some kind of persistence (IndexDB, file storage APIs, ...), which is also a use case I am very interested in.

Indeed. but just like you said I believe the most important usecase for this is WASM (IndexDB).

A possible option: make all the SPARQL evaluation code async and use a dummy runtime on not-async stores that just pool the future until completion (once if everything is implemented properly). This way we would still be able to provide a simple sync API while having an async-ready evaluator usable with async storages. But I don't know what is the cost of making some code "async" if it does not yield and completes immediately. The code will be probably too dynamic to allow LLVM to optimize this "asyncness" away.

Anyway, a channel option might also make sense if we want to have multi-core query evaluation.

**Comment by Tpt** [comment]
After discussion #89, I have made the choice of focusing Oxigraph on the simple disk-based storage use case. Distributed stores will have to be tackled by an other project. However I plan to move some easily reusable parts of Oxigraph in stand-alone crates to make a such project easier.
