### ISSUE TITLE
Implement SPARQL graph store API

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#56]
It might be convenient to implement [SPARQL 1.1 Graph Store HTTP Protocol](https://www.w3.org/TR/sparql11-http-rdf-update/) in Oxigraph server to allow easily fetching and updating the store content.

**Comment by Tpt** [comment]
I have started to implement it. I consider providing the graph store API under the server `/store` path. @ktk does it seems relevant to you? I have never been a huge user of the "Graph Store" protocol.

**Comment by ktk** [comment]
Good question, I have not seen a common pattern in stores so far.
* [Fuseki](https://jena.apache.org/documentation/archive/serving_data/fuseki1.html#server-uri-scheme) provides SPARQL Graph Store under `/data` by default while SPARQL Query is under `/query`. 
* Stardog supports multiple DBs and provides Graph Store via `/dbname` while SPARQL query is under `/dbname/query`.

`/store` works for me, it fits with the protocol spec name.

**Comment by Tpt** [comment]
Done and released as part of Oxigraph 0.2. I have opened #72 about a missing feature.
