### ISSUE TITLE
Implement Concise Bounded Description for SPARQL DESCRIBE

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#61]
Currently `SPARQL DESCRIBE` queries are implemented by returning all triples _s p o_ where _s_ is the described entity. It might be nice to return the entities [Concise Bounded Description](https://www.w3.org/Submission/CBD/) instead in order to avoid returning dandling blank nodes.

**Comment by edmondchuc** [comment]
Implementation in Python's RDFLib for reference. https://github.com/RDFLib/rdflib/pull/1502

**Comment by nicholascar** [comment]
Closing as the CBD function has been resurrected and is now merged!
