### ISSUE TITLE
Rename oxigraph_server CLI to just oxigraph

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#620]
The `oxigraph_server` binary is now not only an HTTP server but a command line tool allowing to manipulate an Oxigraph database (create/load/dump/query/update/compact...). It might be nice to rename it to a more representative (`oxigraph`) and make its cargo package `oxigraph-cli`.

**Comment by Tpt** [comment]
@bollwyvl This will affect oxigraph Conda packages

**Comment by bollwyvl** [comment]
Yeah, no worries there... it'll just fail to build, and should be easy enough to fix.

**Comment by Tpt** [comment]
Done in 0.4.0-alpha.1
