### ISSUE TITLE
Support for gremlin or cypher query as they are widely used

### ISSUE THREAD

**Issue by dgandhi17** [oxigraph/oxigraph#65]
I saw that germlin and cypher query languages are quite similar but they are better because it's been widely used across different tech stack

**Comment by Tpt** [comment]
Both Gremlin and Cypher relies on the [property graph](https://en.wikipedia.org/wiki/Graph_database#Labeled-property_graph) model that is quite different from the [RDF](https://en.wikipedia.org/wiki/Graph_database#Resource_Description_Framework_(RDF)) model that Oxigraph implements.

I disagree about the assumption of this task that SPARQL is not widely used. There are [a lot](https://en.wikipedia.org/wiki/List_of_SPARQL_implementations) of different SPARQL implementations that are fairly compatible with each other, a level of interoperability that is not provided by the property-graph implementations.

Adding Gremlin or Cypher would require a lot of change everywhere in Oxigraph, making it a quite different project. So, I believe that Cypher or Gremlin should be the focus of an other project, letting Oxigraph focus on SPARQL. Imho, having proper query optimization is a much more important goal for Oxigraph than supporting multiple query languages and data models.
