### ISSUE TITLE
How to load and use TTL-Star files?

### ISSUE THREAD

**Issue by windoze** [oxigraph/oxigraph#697]
I have a simple TTL star file:
```
@prefix pfx: <graph://schema/someprefix#> .

pfx:e1 a pfx:entity .
pfx:e2 a pfx:entity .
<<pfx:e1 pfx:connect pfx:e2>>  pfx:edgeProp "some value" .
```

And I loaded into the server:
```
oxigraph_server load -f test.ttl -l test
```

Then I ran the server:
```
oxigraph_server serve -l test
```

Then I opened the web console at http://localhost:7878, then input the query:
```
SELECT * WHERE {
  ?s ?p ?o .
} LIMIT 50
```

After clicking the run button, it showed:
```
e[t].value.replace is not a function
```

I don't quite understand what happened and where I did wrong.

Can anyone help? 

Thanks.

**Comment by Tpt** [comment]
Hi! Thank you for the bug report. The SPARQL query editor and visualizer embedded in Oxigraph server does not support RDF-star at the moment. So, even if your query is perfectly correct the result display box will fail on the data returned by the server. I have opened #698 about it.

**Comment by windoze** [comment]
Thanks for the quick response, now I understand that the error happened on the UI side.

Closing the issue as the function actually works as expected.
