### ISSUE TITLE
backup should be able to take Path

### ISSUE THREAD

**Issue by majidaldo** [oxigraph/oxigraph#699]
In the Python bindings, [backup](https://pyoxigraph.readthedocs.io/en/stable/store.html#pyoxigraph.Store.backup) should be able to take a Path (and not just a string).

**Comment by Tpt** [comment]
Indeed. I forgot this method when adding support for `Path`. I will fix that in the next release.

**Comment by majidaldo** [comment]
Also would be more consistent with Store

**Comment by Tpt** [comment]
Done in 0.4.0-alpha.1
