### ISSUE TITLE
Expose base IRI of parsers?

### ISSUE THREAD

**Issue by labra** [oxigraph/oxigraph#730]
When parsing RDF, would it be possible to expose the base IRI?

I noticed that the prefixes are already exposed in methods like this one:

https://github.com/oxigraph/oxigraph/blob/c2df0b829d8528218ee77733c0ecf49379fb37cc/lib/oxttl/src/turtle.rs#L349

Would it be possible to add a similar method with this signature?

```
 pub fn base_iri(&self) -> &Option<Iri<String>> {
  ...
}
```

**Comment by Tpt** [comment]
Hi! Yes, of course. It's definitely something that should be done.

**Comment by Tpt** [comment]
Released in 0.4.0-alpha.3
