### ISSUE TITLE
[JS] `union-default-graph` query parameter

### ISSUE THREAD

**Issue by ludovicm67** [oxigraph/oxigraph#735]
While reading the changelogs, I saw that the `union-default-graph` query parameter is available since version [0.2.4](https://github.com/oxigraph/oxigraph/blob/main/CHANGELOG.md#024---2021-04-28).

I'm wondering if it would be possible to get a binding for this for JavaScript/Node.JS.

Maybe this can be done by adding an optional argument to the `query` function that is exposed, so that it takes an object of options (like `union-default-graph` that we can set to `true`).

This feature request is from https://github.com/oxigraph/oxigraph/discussions/734

**Comment by Tpt** [comment]
Releases in 0.4.0-alpha.4
