### ISSUE TITLE
flexible alternatives to load_graph and load_dataset

### ISSUE THREAD

**Issue by bddap** [oxigraph/oxigraph#74]
Here is the current [type signature for load_graph](https://github.com/oxigraph/oxigraph/blob/dd040a883188350873df0c1697cd0543d3e13a35/lib/src/store/memory.rs#L330) in `MemoryStore`. It is mirrored in `RocksDbStore` and `SledStore`. The type signature for `load_dataset` is similar.

Please consider this API as it may be a better fit:

```rust
pub fn alternate_load_graph<'a, E>(
    &self,
    triples: impl IntoIterator<Item = Result<Triple, E>>,
    to_graph_name: impl Into<GraphNameRef<'a>>,
) -> Result<(), E>;
```

A few upsides to the suggested api:
- It should make the implementation simpler.
- Stores no longer need to care about parsing. (separation of concerns)
- Scratches a personal itch of mine (I need to reify tuples before inserting them into the graph so I can't directly pass the serialized document.)
- Allows use of arbitrary graph serialization formats, not just `GraphFormat::NTriples`, `GraphFormat::Turtle` and `GraphFormat::RdfXml`

**Comment by Tpt** [comment]
Hi! Thank you for this great idea!

Indeed having a method allowing to load easily a set of triples into a store would be great to avoid this small boilerplate:
```rust
for triple in triples {
   store.insert(&triple.in_graph(to_graph_name))?;
}
```
and allow some optimizations (batch inserts).

However I would be more in favor of keeping a method allowing to easily parse and load a graph: it's a quite common operation so having it directly in the API helps some use cases. It also allows some optimizations that are not currently possible with Oxigraph public API.

About the separation of concerns it's true indeed but the store API already depends on so many things (SPARQL evaluation...) and nothing prevents the user to use their own parsers. And the Rio parsers that Oxigraph use internally are I believe quite small (their only significant dependency is the `quick-xml` library that is also used by Oxigraph for the SPARQL XML results format).

So, what about introducing an `extend` method to directly load an iterator of quads and an `extend_graph` method to load an iterator of triple? The `extend` naming would be to stay close to the [std `Extend` trait](https://doc.rust-lang.org/std/iter/trait.Extend.html).

What do you think about it?

**Comment by bddap** [comment]
I'm about to use the term "blank-node hygiene". "blank-node hygiene" means when a new graph is added, its blank nodes don't get conflated with those already in the store.

`load_graph` and `load_dataset` provide blank-node hygiene by ultimately calling [encode_rio_blank_node](https://github.com/oxigraph/oxigraph/blob/dd040a883188350873df0c1697cd0543d3e13a35/lib/src/store/numeric_encoder.rs#L909) for each blank node.

`extend` would need to provide blank node hygiene to cover my use-case.

If `extend` accepted an iterator over `Result<Quad, E>` (assuming it provides blank-node hygiene) it would be straightforward to plug custom parsers:

<details>
<summary>
</summary>

```rust
// rio_turtle::NQuadsParser: rio_api::parser::QuadsParser
store.extend::<TurtleError>(rio_turtle::NQuadsParser::new(reader).into_iterator(to_oxi_quad))?;

// rio_turtle::NTriplesParser: rio_api::parser::TriplesParser
store.extend_graph::<TurtleError>(
    rio_turtle::NTriplesParser::new(reader).into_iterator(to_oxi_triple),
    graph_name
)?;

// example_crate::JsonldParser: IntoIterator<Item = Result<Triple, JsonldError>>
store.extend_graph::<JsonldError>(example_crate::JsonldParser::new(reader, resolver), graph_name)?;
```
</details>

**Comment by Tpt** [comment]
> `extend` would need to provide blank node hygiene to cover my use-case.

To be consistent with `insert` I would be more in favor of not adding blank node hygiene to `extend` but instead provide a function named something like`make_blank_node_unique` that makes sure that all the blank node in a iterator are unique. This way users would only pay the blank node hygiene price if they want.

Anyway, if you only build blank nodes using the recommended `BlankNode::default` function, blank node hygiene is enforced. If you plan to write a parser you could just use `BlankNode::default()` for anonymous blank nodes and something like `bnodes_map.entry(bnode_id).or_default().clone()` should do the job for "named" blank nodes with `bnodes_map` a `HashMap<String,BlankNode>`. Automatically generated blank nodes are internally a `u128` and are much cheaper to clone and store than blank nodes with a custom ID.

PS: If you plan to implement a JSON-LD parser, I would really like to integrate it into Oxigraph.

**Comment by Tpt** [comment]
The `Store` API allows to insert an iterator of triple with `Store::extend` so I guess this use case is solved. I kept the `load` API to allow some optimizations and good defaults.
