### ISSUE TITLE
impl From<spargebra::Update> for Update

### ISSUE THREAD

**Issue by Natureshadow** [oxigraph/oxigraph#784]
**Is your feature request related to a problem? Please describe.**

I'd like to convert from a spargebra Update to an oxigraph Update, like it is possible for Query.

**Describe the solution you'd like**

I'd like to use a From implementation.

**Describe alternatives you've considered**

```rust
oxigraph::sparql::Update::parse(
    &format!("{}", spargebra_update),                                                                                                                                                                   
    spargebra_update.base_iri.as_deref(), 
).expect("cannot happen if no bugs in spargebra vs. oxigraph");
```

But well, no ;).

**Comment by Tpt** [comment]
Released in 0.4.0-alpha.4
