### ISSUE TITLE
[Question] [`oxrdf`] Casting a `Term` to a `Literal`

### ISSUE THREAD

**Issue by jeswr** [oxigraph/oxigraph#788]
I'm currently trying to build an RDF library for Lean4 (https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/FFI.20with.20rust.20package.20that.20uses.20pthreads/near/418837780). As a first iteration I'm trying to just use the rust parsers / seralizers that you've build and use FFI to call them from lean.

In order to do so - I need to convert `Quads` into a representation that can be passed between languages; to do this I want to get some working code that looks roughly like

```rust
if object.is_literal() {
  let literal = object.as_literal().unwrap();
  if literal.is_language_tagged_literal() {
    ...
  } else {
    ...
  }
}
```

But no such `as_literal` function exists. How can I do this casting?

**Comment by Tpt** [comment]
Hey! [`Term`](https://docs.rs/oxrdf/0.2.0-alpha.2/oxrdf/enum.Term.html) is an enum so you can use `match` to do pattern matching. For example:

```rust
match object {
   Term::NamedNode(iri) => /* do something with iri */,
   Term::BlankNode(id) => /* do something with id */,
   Term::Literal(literal) => {
        let value = literal.value();
        if let Some(language) = literal.language() {
            /* language tagged literal, do something with value and language */
        } else {
           /* regular literal */
        }
    }
}
```

**Comment by jeswr** [comment]
Ah thankyou! (and apologies for my extremely limited knowledge of Rust)
