### ISSUE TITLE
Is something  like Blazegraph GAS searches feasible in the future?  

### ISSUE THREAD

**Issue by fils** [oxigraph/oxigraph#79]
So this is more to satisfy my own curiosity by asking people I am sure understand this far better than I.

First, I'm really enjoying tinkering with Oxigraph in my workflow.   I currently use Blazegraph, but on the arrival of text search, which I see as an active goal, I'd be ready to drop this in for it.  

I do, however, also use these queries:  https://github.com/blazegraph/database/wiki/RDF_GAS_API 

I'm curious, between the pull request for external functions and, perhaps more so, the talk of RDF* support...
Would similar queries potentially be possible at some point?

I've only started to read about RDF*, but I wonder if it alone would enable something similar to these GAS queries to be done.

Thanks for any time and perspective on this..  

Doug

(this likely would have been better for the "discussion" section, but doesn't look like you use them)

**Comment by Tpt** [comment]
Thank you for using Oxigraph! It's great to see people interested!

Oxigraph is still far from Blazegraph performances on complex queries. I hope to fix that is the next few years.

RDF* aims at allowing to use triples as subjet/object of other triples. For example, it allows to write `<< Joe_Biden, presidentOf, USA>> startDate 2021` to state that Joe Biden has been the US president after 2021. The main goal is to allow "facts on edges" just like property graph databases like Neo4J. This is the new name for [Blazegraph "Reification Done Right"](https://github.com/blazegraph/database/wiki/Reification_Done_Right). I believe it's quite disconnected to large scale graph processing provided by Blazegraph GAS API.

About Blazegraph GAS API, it would be nice to support it indeed. However, I was considering keeping Oxigraph in the "embedded database" space (like sqlite) so the main advantage of the processing model of the GAS API, distributed computing, would not apply to Oxigraph. But it would be nice indeed to provide a similar API for doing computations not possible with regular SPARQL like page rank. In any case, I would prefer to write SPARQL optimizers and add full text search and RDF* support before except if someone contributes GAS support. I personally do not have much use for GAS at the moment.

Yes, I just opened the "discussion" space a few weeks ago. There is no much activity around Oxigraph, feel free to start something there if you want.

**Comment by Tpt** [comment]
followed on GitHub discussions #81
