### ISSUE TITLE
Why does `LiteralContent::String` exist as an internal?

### ISSUE THREAD

**Issue by jeswr** [oxigraph/oxigraph#798]
I'm trying to understand this design decision since I'm trying to make the Lean interfaces for RDF similar to the ones implemented here.

Consequently, I'm wondering why `LiteralContent::String` exist as an internal when this could be represented as an `LiteralContent::TypedLiteral` with an `xsd:string` datatype.

**Comment by Tpt** [comment]
The main rational is to be close to RDF 1.0 that had "plain literals" without datatype and optimize the common case of plain string literals. Indeed, it's overlapping with literals with the `xsd:string` datatype, it's why the constructors uses `LiteralContent::String` if the datatype is `xsd:string`.
