### ISSUE TITLE
maybe offer alternative to rio

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#805]
Rio allegedly [has a security issue](https://rustsec.org/advisories/RUSTSEC-2020-0021.html).

Aparently it has been an open issue since 2020, and recently it has been flagged in Debian as a reason for kicking that project from the path of entering next stable release of Debian, along with all its reverse deendencies including Oxigraph.

Therefore: Is it possible for Oxigraph to use something else than rio?

**Comment by jonassmedegaard** [comment]
Oh, silly me: https://github.com/oxigraph/rio used by Oxigraph is something completely different from https://github.com/spacejam/rio affected by the security issue.

Closing as a non-issue.

**Comment by Tpt** [comment]
Yes! Anyway Oxigraph is moving away from oxigraph/rio to use the new oxrdfxml and oxttl crates.
