### ISSUE TITLE
spargebra-0.2.0 alpha3 < spargebra v0.2.8

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#817]
crate spargegra released with oxigraph 0.3.0 is newer than the version released with oxigraph v0.4.0 alha.3.

**Comment by Tpt** [comment]
Thank you for reporting this! Fix: #818

**Comment by Tpt** [comment]
This has been fixed in follow-up alpha releases. https://crates.io/crates/spargebra/versions
