### ISSUE TITLE
Useage of `oxigraph_server` dump

### ISSUE THREAD

**Issue by Luke-ebbis** [oxigraph/oxigraph#824]
I am able to load `ttl` files into a store that have a base prefix of
```
@prefix base:  <http://example.org/> .
```

When I try to dump the store using

```
oxigraph_server dump --format 'ttl' --location results/store/ --graph http://example.org/
```

I don't get any output and no error messages are printed. Am I doing something wrong?

**Comment by Tpt** [comment]
Hey! I would tend to think you are confusing mutliple things here:

Turtle `@prefix` is a syntaxic sugar. If you have
`@prefix base:  <http://example.org/> .`
then `base:foo` will be parsed as `<http://example.org/foo>`.

The `--graph` option of `oxigraph_server dump` is to return only a specific "named graph". If you run this command you should get the full store content:
`oxigraph_server dump --format 'trig' --location results/store/`

**Comment by Luke-ebbis** [comment]
Thank you @Tpt , I managed to get a dump of the database in `trig` format. Just for further learning, what if I want the `--format nt` instead. Then according to the documentation, I must provide a `--graph` argument. However from the documentation and this discussion it is not fully clear what I should write there. Do you know?

**Comment by Tpt** [comment]
Sorry, the documentation is a bit measleading. You can set `--graph default` to dump the default graph and generate a N-Triples file. I am going to improve the doc

**Comment by Luke-ebbis** [comment]
Thank you! Besides this small issue, I found `oxigraph` to be more user friendly than other databases.

**Comment by Tpt** [comment]
> Thank you! Besides this small issue, I found oxigraph to be more user friendly than other databases.

Thank you! This very kind of you!
