### ISSUE TITLE
Quads inserted to SledStore using `transaction()` seems to not add the named graph to the store

### ISSUE THREAD

**Issue by dougli1sqrd** [oxigraph/oxigraph#83]
Hello! I've been playing with oxigraph and it's a lot of fun, but I've run into an issue with getting all the graphs in the system with `store.named_graphs()`.

When I insert a quad into a SledStore using `insert()`, and then check the named graphs with `named_graphs()` I get the newly added named graph.

However, if I use the `transaction()` function and perform the same operation, I then do not see the newly added graph in `named_graph()`.

It's possible I'm doing something wrong, and I'm happy to learn!

For an example, here are two tests that show these cases:
```rust
use oxigraph::SledStore as Store;
use oxigraph::model::{NamedOrBlankNode, Quad, NamedNode};
use oxigraph::store::sled::{SledConflictableTransactionError, SledTransaction};
use std::convert::Infallible;

#[test]
fn test_regular_insert() {
    let store = Store::new().expect("Couldn't make Store");

    // Insert a triple into named graph `<www.example.com>`
    let _ = store.insert(Quad::new(
        NamedNode::new_unchecked("www.example.com/A"),
        oxigraph::model::vocab::rdf::TYPE,
        NamedNode::new_unchecked("www.example.com/B"),
        NamedNode::new_unchecked("www.example.com")
    ).as_ref());

    let q: Vec<_> = store.iter().filter_map(|q| q.ok()).collect();
    println!("{:?}", q);
    assert_eq!(1, q.len());
    let g: Vec<_> = store.named_graphs().filter_map(|g| g.ok()).collect();
    println!("{:?}", g);
    assert_eq!(1, g.len());
    assert_eq!(vec![NamedOrBlankNode::NamedNode(NamedNode::new_unchecked("www.example.com"))], g);
}

#[test]
fn test_transaction_insert() {
    let store = Store::new().expect("Couldn't make Store");

    // Insert a triple into named graph `<www.example.com>`
    let _ = store.transaction(|transaction: SledTransaction| {
        let _ = transaction.insert(Quad::new(
            NamedNode::new_unchecked("www.example.com/A"),
            oxigraph::model::vocab::rdf::TYPE,
            NamedNode::new_unchecked("www.example.com/B"),
            NamedNode::new_unchecked("www.example.com")
        ).as_ref());

        Ok(()) as Result<(), SledConflictableTransactionError<Infallible>>
    });

    let q: Vec<_> = store.iter().filter_map(|q| q.ok()).collect();
    println!("{:?}", q);
    assert_eq!(1, q.len());
    let g: Vec<_> = store.named_graphs().filter_map(|g| g.ok()).collect();
    println!("{:?}", g);
    // These asserts fail
    assert_eq!(1, g.len());
    assert_eq!(vec![NamedOrBlankNode::NamedNode(NamedNode::new_unchecked("www.example.com"))], g);
}
```

Thanks for the help!

**Comment by Tpt** [comment]
Thank you for testing Oxigraph! It is great to see people interested in my pet project.

Sorry for this bug, I indeed forgot to update the named graph index during quad insertion as part of a transaction using Sled. This commit should fix the bug: d9bdc6e4acd83efd6be1f8e9eb3d0c3c204265d7

Oxigraph test coverage should definitely be improved to catch such dumb problems.

**Comment by dougli1sqrd** [comment]
Oh amazing! Thanks so much! Yeah what a fun project, love to see RDF and linked data tech in rust!

I just updated my `cargo.toml` to master oxigraph and both tests pass now!

If you want, feel free to just use those example tests, they're almost verbatim what I wrote to get a minimum test case to demonstrate what I was seeing. Or I can make a PR with these included if you'd rather as well!

**Comment by Tpt** [comment]
Thank you! Great! I have added doctests to `SledStore`: 8fdf1b4abe27bf6ad694de35a682b5cbcd65a550 This way I am both improving documentation and test coverage.
