### ISSUE TITLE
minor nits in README

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#843]
When looking into updating the Debian package for the upcoming v0.4, I noticed a few nits in README files.

Serialization format "RDF XML" is more accurately named "RDF/XML".

The [Oxigraph CLI README](https://github.com/oxigraph/oxigraph/tree/main/cli#oxigraph-cli) says "manipulate an RDF files" - drop the "an" if multiple files are handled, or say "file" if only one is handled at a time.

Cargo.toml for Oxigraph CLI talks about a toolkit, but the README describes it as a CLI tool. The latter seems more accurate.
Also, at blot places is used "command line", where e.g. english Wikipedia uses "command-line". I suggest to use "CLI tool" in Cargo.toml and "command-line tool" in README.

**Comment by jonassmedegaard** [comment]
Yet another nit: Cargo.toml for Oxigraph CLI describes it as "Oxigraph command line toolkit [...]", which I find not really descriptive.
For the Debian packaging short description, I have rephrased that as "RDF graph CLI tool [...]".

**Comment by Tpt** [comment]
Thank you for working on Oxigraph 0.4 and reporting these typos!

**Comment by joepie91** [comment]
Like, #842, should this issue be closed?

**Comment by Tpt** [comment]
Indeed. Thanks
