### ISSUE TITLE
Is it possible, using oxi*, to acess a "foreign" SPARQL endpoint?

### ISSUE THREAD

**Issue by hoijui** [oxigraph/oxigraph#889]
... with that endpoint being an oxigraph DB on an other machine, neo4j or whatever.
I could not find it after a quick search.
If not, is this at all desired at some time in the future?

## My use case

I write a small lib+CLI tool to analyze RDF data, and I want to give the user the ability to provide the data in different ways: as a turtle-file, an oxigraph db, a URL to a serialized RDF file, or a SPARQL endpoint. using oxi* for everything internally, it would be convenient to have this ability.

**Comment by Tpt** [comment]
Yes! Except in the JS/WASM package, [SPARQL federated queries](https://www.w3.org/TR/sparql11-federated-query/) are supported.

Example:
```sparql
SELECT * WHERE {
  SERVICE <http://my_sparql_endpoint> {
    # The query the be executed by the remote SPARQL endpoint  
  }
}
```

**Comment by hoijui** [comment]
eh wow, great!! :-)
thank you!
