### ISSUE TITLE
Oxttl - Compatibility Issues with Turtle Parser and WebAssembly?

### ISSUE THREAD

**Issue by uo271080** [oxigraph/oxigraph#902]
Good morning,

I am having trouble when trying to replicate the example of the Turtle Parser given on the Oxttl documentation. I'm using WebAssembly. Is Oxttl still compatible with it? 

The example:

```
use oxrdf::{NamedNodeRef, vocab::rdf};
use oxttl::TurtleParser;

let file = b"@base <http://example.com/> .
@prefix schema: <http://schema.org/> .
<foo> a schema:Person ;
    schema:name \"Foo\" .
<bar> a schema:Person ;
    schema:name \"Bar\" .";

let schema_person = NamedNodeRef::new("http://schema.org/Person").unwrap();
let mut count = 0;
for triple in TurtleParser::new().parse_read(file.as_ref()) {
    let triple = triple.unwrap();
    if triple.predicate == rdf::TYPE && triple.object == schema_person.into() {
        count += 1;
    }
}
assert_eq!(2, count);
```

I am receiving the following errors:

**Error 1:**
`can't compare `oxrdf::named_node::NamedNode` with `NamedNodeRef<'_>`
the trait `PartialEq<NamedNodeRef<'_>>` is not implemented for `oxrdf::named_node::NamedNode`
the following other types implement trait `PartialEq<Rhs>`:
  <oxrdf::named_node::NamedNode as PartialEq>
  <oxrdf::named_node::NamedNode as PartialEq<oxrdf::named_node::NamedNodeRef<'_>>>
  <oxrdf::named_node::NamedNode as PartialEq<str>>
  <oxrdf::named_node::NamedNode as PartialEq<&str>>`

**Error 2**
`the trait bound `oxrdf::triple::Term: From<NamedNodeRef<'_>>` is not satisfied
the following other types implement trait `From<T>`:
  <oxrdf::triple::Term as From<oxrdf::blank_node::BlankNode>>
  <oxrdf::triple::Term as From<oxrdf::blank_node::BlankNodeRef<'_>>>
  <oxrdf::triple::Term as From<oxrdf::literal::Literal>>
  <oxrdf::triple::Term as From<oxrdf::literal::LiteralRef<'_>>>
  <oxrdf::triple::Term as From<oxrdf::named_node::NamedNode>>
  <oxrdf::triple::Term as From<oxrdf::named_node::NamedNodeRef<'_>>>
  <oxrdf::triple::Term as From<oxrdf::triple::NamedOrBlankNode>>
  <oxrdf::triple::Term as From<oxrdf::triple::NamedOrBlankNodeRef<'_>>>
and 3 others
required for `NamedNodeRef<'_>` to implement `Into<oxrdf::triple::Term>``

![image](https://github.com/oxigraph/oxigraph/assets/60232864/3bbd292a-b477-4d24-bb24-bf70abbe1caa)

Maybe I am doing something wrong as I am just starting with Rust.

Thanks in advanced!

**Comment by Tpt** [comment]
Hi! Just to check, are you using `oxrdf` 0.1 or `oxrdf` 0.2-alpha.X? `oxttl` is using `oxrdf` 0.2 alpha versions and cargo happily installs multiple incompatible versions of the same library but their type are not compatible together (e.g. not possible to compare the `NamedNode`  struct from v0.1 with the `NamedNode` struct from v0.2)

**Comment by uo271080** [comment]
Hi, that was the problem! 

Thanks :)
