### ISSUE TITLE
Parsing comments and row&column info

### ISSUE THREAD

**Issue by hoijui** [oxigraph/oxigraph#908]
I want to write a linter for RDF files (especially/mainly Turtle).
It would primarily be applied to ontologies.

A base requirement for this would be, to be able to parse the files in maximum detail, including comments (native file-format comments like `# foo` in Turtle, not `rdfs:comment "foo" ;`), and to get line and column number for each parsed item.
`oxttl` (& co.) does not currently support that, and I found that this is generally missing in parsers.
There are of course good reasons why this is missing:

- parsing performance, especially memory usage
- code complexity
- in most scenarios, this info is not required

How feasible is it, and how keen would you be to accept a PR that implements this, hidden behind two features (comments-parsing & row-column), or what alternatives do you suggest?

**Comment by Tpt** [comment]
Thank you for this proposal! `oxttl` is strongly focused on fast streaming parsing I am afraid moving into the lossless parsing direction is going to be very painful and we will end up with a very ackward codebase. I tend to think that starting from scratch a parser would be easier. I wrote [an auto formatter for Turtle](https://github.com/helsing-ai/turtlefmt) and used [tree-sitter](https://tree-sitter.github.io/tree-sitter/) for that (see [the grammar](https://github.com/helsing-ai/turtlefmt/tree/main/tree-sitter))
