### ISSUE TITLE
panicks test blank_node::tests::test_size_and_alignment on i386

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#916]
Building v0.4.0-alpha.7 on Debian build-daemons panicks in checking the testsuite on i386 architecture:
```
thread 'blank_node::tests::test_size_and_alignment' panicked at lib/oxrdf/src/blank_node.rs:412:9:
assertion `left == right` failed
  left: 52
 right: 56
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Tpt** [comment]
Should be fixed by #918

**Comment by jonassmedegaard** [comment]
Yes, I can confirm that that fix works: I cherry-picked the (identical) earlier commit ba32a0d and [status page for oxigraph](https://tracker.debian.org/pkg/oxigraph) indicates that it might finally enter Debian testing within a few days.

**Comment by jonassmedegaard** [comment]
Whoops, I thought this was about #913 - I will know in few hours how this one fares (but seems so simple that even I can follow what the patch does, so looks promising)

**Comment by jonassmedegaard** [comment]
Yes, succesfully builds also for 32-bit arches. Thanks!
