### ISSUE TITLE
[FEATURE] Python custom function support for PyOxigraph

### ISSUE THREAD

**Issue by ashleysommer** [oxigraph/oxigraph#935]
My goal is to use PyOxigraph to address some SPARQL performance issues in PySHACL (which uses RDFLib SPARQL executor).
I want to use the PyOxigraph SPARQL executor to replace the RDFLib SPARQL executor for `SPARQLConstraint` and `SPARQLFunction` features of PySHACL to remove that bottleneck.

The main hurdle I'm seeing is the lack of SPARQL Custom Functions in PyOxigraph. I am aware the Rust query interface allows calling with custom Rust functions, but this feature is not available in the Python library.

PySHACL uses the RDFLib `register_custom_function` method to register python callbacks that are called from `SPARQLConstraint` queries, that can in-turn execute shape-graph-defined `SPARQLFunction`s.

 I this a planned feature? I searched the issue tracker and didn't see a similar feature request. I understand this is not a simple feature to add, it will require some complex PyO3 wizardry to call from the Rust SPARQL executor back into user-defined python code.

**Comment by Tpt** [comment]
Thank you for trying Oxigraph! This project sounds great! I have an implementation nearly ready in #938 
The trickest thing was to upgrade to Python type stubs generator to support the `Callable` syntex

**Comment by ashleysommer** [comment]
Wow! That was fast. Thank you so much for this, I can't wait to try it out.

**Comment by Tpt** [comment]
Released as part of 0.4.0-alpha.8
