### ISSUE TITLE
Python "load" and "bulk_load" both use transactional loading

### ISSUE THREAD

**Issue by marvindroid** [oxigraph/oxigraph#939]
Using pyoxigraph version 0.4.0a7

Loading a large file (GB's) in Python using `store.bulk_load` consumes vast amounts of memory.
Looking at code in `python\src\store.rs`, both **load** and **bulk_load** functions have identical code which means both are calling 
`store.load_from_read(parser, input)`
which uses transactional loading whereas `store.bulk_extend` uses `bulk_loader()`.

Loading a 2.4GB n-triple file containing  just on a million triples :
- in Rust (using oxigraph 0.4.0a7) `store.bulk_loader` takes 10.2 seconds and minimal additional memory
- in Python using `store.bulk_load` takes 319 seconds and uses 23GB of memory while doing it.

**Comment by Tpt** [comment]
Indeed. My bad. I have opened #940

**Comment by Tpt** [comment]
Released as part of 0.4.0-alpha.8
