### ISSUE TITLE
Enpoint access to pyoxigraph RDF Store

### ISSUE THREAD

**Issue by ch-sander** [oxigraph/oxigraph#948]
A beginner's question: I have successfully loaded my RDF in a Store with pyoxigraph (local directory).

In my docker compose I have put 
```yaml
    volumes:
      - ./oxigraph_store:/data
```
I can access my data by `store.query` with pyoxigraph but any access via API `(http://localhost:7878/query`) fails.

**How can I access my RDF store via the endpoint?**

**Comment by ch-sander** [comment]
a file permission issue. The oxigraph server cannot run in ro-mode

**Comment by Tpt** [comment]
You can use the "serve-read-only" command instead of "serve" to serve a directory without write access

**Comment by ch-sander** [comment]
Thanks, that solved the initial problem!
I would like to use the bulk load from pyoxigraph (as working in a flask environment) and have the API endpoint as a read-only for a ResearchSpace instance.
Yet:

- the oxigraph docker container needs to restart to discover the new data from the pyoxigraph `Store`
- the /store call from the endpoint which might be designed for bulk upload doesn't perform on my data, I get a 201 but no data is returned from queries. Some of the .log files are around 400mb, so I suspect them to decode the errors of the parser. I tried with a decent file both in ttl and trig (50mb in ttl). In smaller files, it works. But without being able to read the logs, I would not like to start graph per graph to catch the problem. blazegraph can load any of then, and they were parsed from json-ld with rdflib.

If you have any idea how I could have such a dynamic interchange or interface between the pyoxigraph Store and a public read-only sparql endpoint, while the pyoxigraph app is run in the same docker network as the oxigraph service...

Otherwise a great app that is apt to replace blazegraph (my own test actually show a huge performance difference).

**Comment by Tpt** [comment]
Amazing!

> the /store call from the endpoint which might be designed for bulk upload doesn't perform on my data, I get a 201 but no data is returned from queries.

Beware, if you POST a RDF file like Turtle or NTriples, the SPARQL graph store HTTP protocol specifies that they get inserted into a new named graph and not the default graph. The 201 response should provide a `Location` header with the created graph name. To add triples to the default graph, you should POST to `/store?default`. It's a quite confusing behavior but I assumed not following the standard would be even more confusing.

> the oxigraph docker container needs to restart to discover the new data from the pyoxigraph Store

Yes, the "read only" mode stays frozen at the time where the server is started. If you want automated discovery of the new data there is the "secondary" mode (`serve-secondary` command) that will automatically discover new data. However there might be some consistency issues with only part of the updated data get served while the secondary instance updates and there are some bad bugs I have not managed to fix yet with RocksDB 9 (but Oxigraph still ships with RocksDB 8 that seems to work fine).

**Comment by ch-sander** [comment]
Fantastic: `?default` did the trick -- although for trig upload I get a `No supported content Content-Type given: application/trig`. Not a problem. pyoxigraph's `bulk_load` takes trig but I havent't been able to query the data afterwards. It seems only to happen with very large trig files. All turtle files (same content as trig) pass with no problem. Also, the `bulk_load` appears to be much faster than the CLI: 15.72525824701006 vs 73.92483528499724s!.

**Comment by Tpt** [comment]
> although for trig upload I get a No supported content Content-Type given: application/trig. Not a problem. 

Yes, this is a limitation in oxigraph 0.3. Oxigraph 0.4 should fix that.

**Comment by ch-sander** [comment]
I confirm, the `serve-secondary` works but only took 1088521 of the total of 1225120 triples before a restart of the service. 

**Is there any way to force a reload of the store without restarting the docker container?**

**Comment by Tpt** [comment]
Sadly not, the secondary database should synchronize with the primary before every read transaction (including SPARQL queries). Missing triples is weird and looks like a bug.

**Comment by ch-sander** [comment]
I'll try to reproduce and if persistent I will let you know
