### ISSUE TITLE
Geo functions

### ISSUE THREAD

**Issue by ch-sander** [oxigraph/oxigraph#953]
Is it possible to set up geo functions for oxigraph?

http://www.opengis.net/def/function/geosparql/

**Comment by Tpt** [comment]
Oxigraph provides an API to declare custom SPARQL function so a basic implementation should not be hard to write.

Sadly, no one has step up to do it yet and I am not a GeoSPARQL user so I won't commit to do it except if someone sponsors this work (there are a lot of other things I would like to fix/improve that would be way more useful for me).

Sorry for that.

Closing as duplicate of #172
