### ISSUE TITLE
Timeout for queries (error message & setting) #610 

### ISSUE THREAD

**Issue by ch-sander** [oxigraph/oxigraph#954]
I feel the built-in YASGUI interface also prompts a _Unable to get response from endpoint. Possible reasons:_ message if the endpoint just timed out.

1. Suggestion: add this as a reason to the list (maybe for YASGUI to fix)
2. Question: is there a native way to define the timeout through oxigraph settings directly or this this only for the nginx route to the API endpoint to be defined?

**Comment by ch-sander** [comment]
see also https://github.com/sparna-git/Sparnatural/issues/610

**Comment by tfrancart** [comment]
For YasGUI I don't know.
For Sparnatural the queries sent to populate dropdown lists or autocomplete fields are using the Javascript `fetch` method under the hood. My understanding is that this method will use the default timeout time of the browser (?)

**Comment by ch-sander** [comment]
> For YasGUI I don't know.
> For Sparnatural the queries sent to populate dropdown lists or autocomplete fields are using the Javascript `fetch` method under the hood. My understanding is that this method will use the default timeout time of the browser (?)

Yes, definitely not a sparnatural issue, sorry for cross posting

**Comment by Tpt** [comment]
Hey! Thank you for using Oxigraph. The Oxigraph HTTP server has no time out system, if queries are timing out in YASGUI it's because the browser request timeout or a timeout in a proxy.
