### ISSUE TITLE
Integration with researchSpace

### ISSUE THREAD

**Issue by ch-sander** [oxigraph/oxigraph#957]
**Is your feature request related to a problem? Please describe.**
I want to make oxigraph the endpoint of [ResearchSpace](https://github.com/researchspace/researchspace) @dianat
I have set up the [docker container](https://github.com/DHI-Roma/researchspace-docker-compose-oxigraph/blob/master/basic/docker-compose.yml) including the basic [oxigraph yaml](https://github.com/oxigraph/oxigraph/tree/main/cli).
`-Dconfig.environment.sparqlEndpoint=http://oxigraph:7878/query ` set in `PLATFORM_OPTS`

**Describe the solution you'd like**
The container starts but Jetty doesn't load (which it does with blazegraph, the default setup). In the logs it make me suspicious that during the test for the endpoint, I read

```
(RepositoryManager.java:265) - Initializing HTTP Sparql Repository with URL: http://oxigraph:7878/query.
...
org.eclipse.rdf4j.repository.RepositoryException: You should set the 'query' parameter
...
at org.eclipse.rdf4j.repository.sparql.query.SPARQLUpdate.execute(SPARQLUpdate.java:41)
```

As other endpoints fail, this setup seems to load but "You should set the 'query' parameter" is the default prompt if you call `/query` qithout any query -- which isn't what ResearchSpace does, I assume.

**Describe alternatives you've considered**
`-Dconfig.environment.sparqlEndpoint=http://localhost:7878/query `
oxigraph ports `"7878:8080"`
including nginx in the container

**Additional context**
Please link to other systems implementing the feature, specification of it if it exists and/or existing documentation about this feature.

**Comment by ch-sander** [comment]
Cross-post at https://github.com/researchspace/researchspace-docker-compose/issues/3

**Comment by Tpt** [comment]
I think it's because ResearchSpace tries to run SPARQL updates using the provided endpoint (`http://localhost:7878/query`) that only supports SPARQL queries. SPARQL updates should be sent to `http://localhost:7878/update`

**Comment by ch-sander** [comment]
that returns another (hopefully insightful) error:
` Request failed with status 404: http://oxigraph:7878/update?query=SELECT+*+WHERE+%7B+%3Fa+%3Fb+%3Fc+%7D+LIMIT+1 . `

**Comment by ch-sander** [comment]
I suspect ResearchSpace cannot be untied from blazegraph and supports different endpoints only as [repositories](https://documentation.researchspace.org/resource/Help:RepositoryManager)

**Comment by aindlq** [comment]
ResearchSpace supports all repositories that can be used through https://github.com/eclipse-rdf4j/rdf4j, including ability to use separate endpoints for query/update. See https://github.com/researchspace/researchspace-docker-compose/issues/3#issuecomment-2282257390

**Comment by ch-sander** [comment]
> ResearchSpace supports all repositories that can be used through https://github.com/eclipse-rdf4j/rdf4j, including ability to use separate endpoints for query/update. See https://github.com/researchspace/researchspace-docker-compose/issues/3#issuecomment-2282257390 
> 

@Tpt I assume oxigraph thus qualifies for ResearchSpace?

**Comment by ch-sander** [comment]
As seen from @aindlq's fix https://github.com/researchspace/researchspace-docker-compose/issues/3#issuecomment-2299908804, there some issues with oxigraph itself. Are those necessary limits or bugs? @Tpt
