### ISSUE TITLE
oxrdf & oxrdfio releases seem to be incompatible

### ISSUE THREAD

**Issue by hoijui** [oxigraph/oxigraph#978]
It look oxrdfio 0.1.0-alpha.7 (which I think is the latest release?) uses (and requires) oxrdf 0.2.0-alpha.6, while it is not compatible with oxrdf 0.1.7 (which is the latest non-alpha release), as one uses `oxrdf::Subject` and the other `oxrdf::triple::Subject`.

I imagine this is a cumbersome-to-solve-nicely issue with your conversion to oxrdf 0.2. As a workaround, I will just use oxrdf 0.2.0-alpha.6 for now, which works for me so far.

Thanks again for your great work on all this!

**Comment by Tpt** [comment]
Thank you for this nice message! Indeed, using oxrdf 0.2 is the easiest way. I hope to cut a stable release soon.

**Comment by Tpt** [comment]
v0.4.0 was released a few weeks ago. Closing.
