### ISSUE TITLE
Access to underlying sled flush functionality 

### ISSUE THREAD

**Issue by allforabit** [oxigraph/oxigraph#99]
I'm using oxigraph in an Android app with the sled backend and it's working quite well but doesn't seem to be flushing to save the data to disk. My understanding is that sled only enables auto flushing on some OS's: https://github.com/spacejam/sled/blob/main/src/context.rs It's not much of a problem to flush it manually. However I'm not sure if it's possible to access the sled db to do this. 

I'm very new to rust (I've just started really) so I could be missing something obvious. Thanks very much!

**Comment by Tpt** [comment]
Hi! It's great to ear that Oxigraph is working on Android! To say the truth I have not used Oxigraph much myself outside of Linux. Oxigraph does not expose the Sled [`flush`](https://docs.rs/sled/0.34.6/sled/struct.Db.html#method.flush) method. I am going to add it to the `SledStore` API. This way it should be possible to use the Sled storage on all targets. I don't know if background auto flushing is possible on Android, it might be nice to open an issue about it in the [Sled project](https://github.com/spacejam/sled/).

**Comment by allforabit** [comment]
Brilliant thanks very much, that should do the trick. Will fully confirm that it's working on Android once that's in place. I'm really enjoying straightforward it is to use all the rust stuff in Android. https://github.com/bbqsrc/cargo-ndk in particular makes things extremely smooth. It's a massive improvement on trying to integrate c and c++ libs (e.g. I tried using oxigraph with rocksdb and hit a wall of errors that I wouldn't know where to begin figuring out!!!)

Yes I'll open an issue there as well as having autoflush would be really nice to have.

**Comment by allforabit** [comment]
Here's the issue over on the Sled project: https://github.com/spacejam/sled/issues/1328

**Comment by Tpt** [comment]
I have released v0.2.4 with [`flush`](https://docs.rs/oxigraph/0.2.4/oxigraph/store/sled/struct.SledStore.html#method.flush) and [`flush_async`](https://docs.rs/oxigraph/0.2.4/oxigraph/store/sled/struct.SledStore.html#method.flush_async) methods.
