### ISSUE TITLE
an implementor of Write is a writer

### ISSUE THREAD

**Issue by lolbinarycat** [oxigraph/oxigraph#992]
`dump_to_write` is a slightly confusing name, as `Write` is a verb, not a noun.

the terms "reader" and "writer" are described in the standard library docs: https://doc.rust-lang.org/nightly/std/io/index.html#read-and-write.

**Comment by Tpt** [comment]
Thank you for raising this. In my mind `dump_to_write` is a shortand for `dump_to_a_write_implementation`. But it's indeed confusing. Do you think `dump_to_writer` is better? I am not an English native speaker.

**Comment by lolbinarycat** [comment]
`dump_to_writer` would indeed be more clear, or possibly even `dump_to`, and let the function signature convey that it's dumping to a writer.

**Comment by Tpt** [comment]
Thank you! I don't like plain `dump_to` because I might need to add extra targets in the future (just like we have `parse_from_slice`...)

**Comment by lolbinarycat** [comment]
fair!

**Comment by Tpt** [comment]
I have made quite a bit of renames in the new release: https://docs.rs/oxrdfio/0.1.0-rc.2/oxrdfio/

**Comment by Tpt** [comment]
Closing, feel free to reopen if you think it can be improved further
